{0}{25}Hello!
{0}{25}{y:i}Hello!
{0}{25}{y:b}Hello!
{0}{25}{y:u}Hello!
{0}{25}{y:s}Hello!
{0}{25}{f:fontname}Hello!
{0}{25}{f:Arial}Hello!
{0}{25}{s:size}Hello!
{0}{25}{s:10}Hello!
{0}{25}{c:$BBGGRR}Hello!
{0}{25}{c:$0000FF}Hello!
{0}{25}{P:X,Y}Hello!
{0}{25}Hello! How are you?
{0}{25}Hello!|How are you?
{0}{25}{Y:i}Hello!|How are you?
{0}{25}{y:i}Hello!|{y:b}How are you?
{0}{25}{c:$0000ff}{y:b,u}{f:DeJaVuSans}{s:12}Hello!
