/*********************************************************/
/* This file is automatically generated by running the   */
/* buildhtmlstrings.sh script which parses translatable  */
/* strings from .qsp and .qjs files under the html       */
/* subdirectory using getTransStringsFromFile.pl.  This  */
/* file should be regenerated before running lupdate in  */
/* the i18n directory to regenerate the i18n/*.ts files. */
/*********************************************************/

void html_strings_null() {
    /* ./menu.qsp */
    QObject::tr("API"),
    QObject::tr("Advanced Setup"),
    QObject::tr("Backend Status"),
    QObject::tr("Change Password"),
    QObject::tr("Channel Editor"),
    QObject::tr("Channel Service"),
    QObject::tr("Content Service"),
    QObject::tr("DVR Service"),
    QObject::tr("Database"),
    QObject::tr("Database Tools"),
    QObject::tr("Expert/Dev Setup"),
    QObject::tr("General"),
    QObject::tr("GetRecorded() Example"),
    QObject::tr("GetStorageGroups()"),
    QObject::tr("Guide Data"),
    QObject::tr("Guide Data Sources"),
    QObject::tr("Guide Service"),
    QObject::tr("Hardware Profile"),
    QObject::tr("Information"),
    QObject::tr("Job Queue"),
    QObject::tr("Myth Service"),
    QObject::tr("Overview"),
    QObject::tr("Recording Devices"),
    QObject::tr("Send a Message"),
    QObject::tr("Server Side Scripting"),
    QObject::tr("Setup"),
    QObject::tr("Setup Wizard"),
    QObject::tr("Storage Groups"),
    QObject::tr("System Events"),
    QObject::tr("Utilities"),
    QObject::tr("WSDL Links"),
    QString()
}
