#!/bin/sh
#
# cpsvndir: recursive directory copy excluding .svn sub dirs.


if [ -z "$1" -o -z "$2" ]; then
    echo "Usage: $0 source-dir destination-dir"
    exit -1
fi

# Some shells don't set EUID
if [ -z "$EUID" ]; then
    if [ -x /usr/bin/id ]; then EUID=`id -u` ;fi
    if [ -z "$EUID" ];     then EUID=$USER   ;fi
    if [ -z "$EUID" ];     then EUID=0       ;fi  # Will fail if not root
fi

# Do similarly for EGID
if [ -z "$EGID" ]; then
    if [ -x /usr/bin/id ]; then EGID=`id -g` ;fi
    if [ -z "$EGID" ];     then EGID=0       ;fi  # Will fail if not root
fi

# Build directory structure
IFS=$'\012'
for directory in $(find "$1" -path '*/.svn' -prune -or -type d -print); do
    mkdir -p "$2/${1##*/}/${directory/#$1}"
done

# Copy files
for file in $(find "$1" -path '*/.svn' -prune -or ! -type d -print); do
    cp -pR "$file" "$2/${1##*/}/${file/#$1}"
    chown $EUID:$EGID "$2/${1##*/}/${file/#$1}" &> /dev/null
    chmod +r "$2/${1##*/}/${file/#$1}" &> /dev/null
done

exit 0
