######################################################################
# Automatically generated by qmake (1.03a) Mon Sep 9 21:00:20 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = mythgame theme i18n
