######################################################################
# Automatically generated by qmake (1.02a) Tue Jul 16 20:59:39 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS  = libNuppelVideo libmythtv mythdialog mythepg mythtv mythfrontend
SUBDIRS += menutest
