######################################################################
# Automatically generated by qmake (1.02a) Tue Jul 16 20:59:39 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += libavcodec libNuppelVideo libmythtv filters mythdialog mythepg 
SUBDIRS += menutest mythfilldatabase mythtv mythfrontend
