######################################################################
# Automatically generated by qmake (1.02a) Mon Jul 8 22:32:30 2002
######################################################################

TEMPLATE = app
CONFIG += thread
target.path = /usr/local/bin
INSTALLS = target

include (../../settings.pro)

INCLUDEPATH += ../../libs
LIBS += -L../../libs/libmyth -lmyth

# Input
SOURCES += main.cpp
