USE mythconverg;

ALTER TABLE musicmetadata ADD COLUMN rating INT UNSIGNED NOT NULL DEFAULT 5;
ALTER TABLE musicmetadata ADD COLUMN lastplay TIMESTAMP NOT NULL;
ALTER TABLE musicmetadata ADD COLUMN playcount INT UNSIGNED NOT NULL DEFAULT 0;
