######################################################################
# Automatically generated by qmake (1.04a) Mon Dec 9 23:49:41 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = mythvideo mtd i18n theme
