######################################################################
# Automatically generated by qmake (1.02a) Tue Jul 16 20:59:39 2002
######################################################################

TEMPLATE = subdirs
CONFIG += ordered

# Directories
SUBDIRS += libavutil libavcodec libavformat libmythsamplerate 
SUBDIRS += libmythsoundtouch libmythmpeg2 libmythdvdnav
SUBDIRS += libmyth libmythtv libmythui libmythfreemheg
