# Makefile for mythzmserver 
#

mythzmserver_objects =  mythzmserver.o zmserver.o


all : mythzmserver 

mythzmserver: $(mythzmserver_objects)
	g++ -o mythzmserver $(mythzmserver_objects) $(shell mysql_config --libs)


mythzmserver.o: mythzmserver.cpp
zmserver: zmserver.cpp

clean:
	rm -f *.o mythzmserver