DATA     = ENVCAN-Stations.xml ENVCANParser.pm ENVCANLocation.pm ENVCAN_icons
DATA    += ENVCANMapSearch.pm ENVCAN-Maps.xml

SCRIPTS  = envcan.pl envcan_animaps.pl envcan_maps.pl

include ../Makefile.inc

