#ifndef TV_ACTIONS_H
#define TV_ACTIONS_H

#define ACTION_PLAYBACK      "PLAYBACK"
#define ACTION_STOP          "STOPPLAYBACK"
#define ACTION_DAYLEFT       "DAYLEFT"
#define ACTION_DAYRIGHT      "DAYRIGHT"
#define ACTION_PAGELEFT      "PAGELEFT"
#define ACTION_PAGERIGHT     "PAGERIGHT"
#define ACTION_TOGGLEPGORDER "TOGGLEEPGORDER"
#define ACTION_CLEAROSD      "CLEAROSD"
#define ACTION_PAUSE         "PAUSE"
#define ACTION_CHANNELUP     "CHANNELUP"
#define ACTION_CHANNELDOWN   "CHANNELDOWN"
#define ACTION_SEEKRWND      "SEEKRWND"
#define ACTION_SEEKFFWD      "SEEKFFWD"

#define ACTION_TOGGLESTUDIOLEVELS "TOGGLESTUDIOLEVELS"
#define ACTION_TOGGLEUPMIX        "TOGGLEUPMIX"
#define ACTION_TOGGLERECORD       "TOGGLERECORD"
#define ACTION_TOGGLEFAV          "TOGGLEFAV"
#define ACTION_TOGGLECHANCONTROLS "TOGGLECHANCONTROLS"
#define ACTION_TOGGLERECCONTROLS  "TOGGLERECCONTROLS"
#define ACTION_TOGGLEINPUTS       "TOGGLEINPUTS"

#define ACTION_GUIDE             "GUIDE"
#define ACTION_FINDER            "FINDER"
#define ACTION_TOGGLESLEEP       QString("TOGGLESLEEP")
#define ACTION_PLAY              "PLAY"
#define ACTION_JUMPPREV          "JUMPPREV"
#define ACTION_JUMPREC           QString("JUMPREC")
#define ACTION_VIEWSCHEDULED     "VIEWSCHEDULED"
#define ACTION_SIGNALMON         "SIGNALMON"

#define ACTION_JUMPTODVDROOTMENU    "JUMPTODVDROOTMENU"
#define ACTION_JUMPTOPOPUPMENU      "JUMPTOPOPUPMENU"
#define ACTION_JUMPTODVDCHAPTERMENU "JUMPTODVDCHAPTERMENU"
#define ACTION_JUMPTODVDTITLEMENU   "JUMPTODVDTITLEMENU"

#define ACTION_EXITSHOWNOPROMPTS "EXITSHOWNOPROMPTS"

/* Interactive Television keys */
#define ACTION_MENURED    "MENURED"
#define ACTION_MENUGREEN  "MENUGREEN"
#define ACTION_MENUYELLOW "MENYELLOW"
#define ACTION_MENUBLUE   "MENUBLUE"
#define ACTION_TEXTEXIT   "TEXTEXIT"
#define ACTION_MENUTEXT   "MENUTEXT"
#define ACTION_MENUEPG    "MENUEPG"

/* Editing keys */
#define ACTION_CLEARMAP     "CLEARMAP"
#define ACTION_INVERTMAP    "INVERTMAP"
#define ACTION_SAVEMAP      "SAVEMAP"
#define ACTION_LOADCOMMSKIP "LOADCOMMSKIP"
#define ACTION_NEXTCUT      "NEXTCUT"
#define ACTION_PREVCUT      "PREVCUT"
#define ACTION_BIGJUMPREW   "BIGJUMPREW"
#define ACTION_BIGJUMPFWD   "BIGJUMPFWD"

/* Teletext keys */
#define ACTION_NEXTPAGE         "NEXTPAGE"
#define ACTION_PREVPAGE         "PREVPAGE"
#define ACTION_NEXTSUBPAGE      "NEXTSUBPAGE"
#define ACTION_PREVSUBPAGE      "PREVSUBPAGE"
#define ACTION_TOGGLETT         "TOGGLETT"
#define ACTION_MENUWHITE        "MENUWHITE"
#define ACTION_TOGGLEBACKGROUND "TOGGLEBACKGROUND"
#define ACTION_REVEAL           "REVEAL"

/* Visualisations */
#define ACTION_TOGGLEVISUALISATION "TOGGLEVISUALISATION"

#endif // TV_ACTIONS_H
