#ifndef GLOBALS_H_
#define GLOBALS_H_

#include "mythmetaexp.h"

META_PUBLIC extern const QString VIDEO_CATEGORY_UNKNOWN;
META_PUBLIC extern const QString VIDEO_DIRECTOR_UNKNOWN;
META_PUBLIC extern const QString VIDEO_GENRE_UNKNOWN;
META_PUBLIC extern const QString VIDEO_COUNTRY_UNKNOWN;
META_PUBLIC extern const QString VIDEO_CAST_UNKNOWN;
META_PUBLIC extern const QString VIDEO_YEAR_UNKNOWN;
META_PUBLIC extern const QString VIDEO_RUNTIME_UNKNOWN;

META_PUBLIC extern const QString VIDEO_CATEGORY_DEFAULT;
META_PUBLIC extern const QString VIDEO_DIRECTOR_DEFAULT;
META_PUBLIC extern const QString VIDEO_INETREF_DEFAULT;
META_PUBLIC extern const QString VIDEO_COVERFILE_DEFAULT;
META_PUBLIC extern const QString VIDEO_TRAILER_DEFAULT;
META_PUBLIC extern const QString VIDEO_SCREENSHOT_DEFAULT;
META_PUBLIC extern const QString VIDEO_BANNER_DEFAULT;
META_PUBLIC extern const QString VIDEO_FANART_DEFAULT;
META_PUBLIC extern const QString VIDEO_RATING_DEFAULT;
META_PUBLIC extern const QString VIDEO_PLOT_DEFAULT;
META_PUBLIC extern const QString VIDEO_CAST_DEFAULT;

META_PUBLIC extern const QString JUMP_VIDEO_MANAGER;
META_PUBLIC extern const QString JUMP_VIDEO_BROWSER;
META_PUBLIC extern const QString JUMP_VIDEO_TREE;
META_PUBLIC extern const QString JUMP_VIDEO_GALLERY;
META_PUBLIC extern const QString JUMP_VIDEO_DEFAULT;

META_PUBLIC extern const QString JUMP_GALLERY_DEFAULT;

META_PUBLIC extern const QString DEFAULT_VIDEOSTARTUP_DIR;

#endif // GLOBALS_H_
