#ifndef GLOBALS_H_
#define GLOBALS_H_

#include "mythexp.h"

extern const QString VIDEO_CATEGORY_UNKNOWN MPUBLIC;
extern const QString VIDEO_DIRECTOR_UNKNOWN MPUBLIC;
extern const QString VIDEO_GENRE_UNKNOWN MPUBLIC;
extern const QString VIDEO_COUNTRY_UNKNOWN MPUBLIC;
extern const QString VIDEO_CAST_UNKNOWN MPUBLIC;
extern const QString VIDEO_YEAR_UNKNOWN MPUBLIC;
extern const QString VIDEO_RUNTIME_UNKNOWN MPUBLIC;

extern const QString VIDEO_CATEGORY_DEFAULT MPUBLIC;
extern const QString VIDEO_DIRECTOR_DEFAULT MPUBLIC;
extern const QString VIDEO_INETREF_DEFAULT MPUBLIC;
extern const QString VIDEO_COVERFILE_DEFAULT MPUBLIC;
extern const QString VIDEO_TRAILER_DEFAULT MPUBLIC;
extern const QString VIDEO_SCREENSHOT_DEFAULT MPUBLIC;
extern const QString VIDEO_BANNER_DEFAULT MPUBLIC;
extern const QString VIDEO_FANART_DEFAULT MPUBLIC;
extern const QString VIDEO_RATING_DEFAULT MPUBLIC;
extern const QString VIDEO_PLOT_DEFAULT MPUBLIC;
extern const QString VIDEO_CAST_DEFAULT MPUBLIC;

extern const QString JUMP_VIDEO_MANAGER MPUBLIC;
extern const QString JUMP_VIDEO_BROWSER MPUBLIC;
extern const QString JUMP_VIDEO_TREE MPUBLIC;
extern const QString JUMP_VIDEO_GALLERY MPUBLIC;
extern const QString JUMP_VIDEO_DEFAULT MPUBLIC;

extern const QString DEFAULT_VIDEOSTARTUP_DIR MPUBLIC;

#endif // GLOBALS_H_
