######################################################################
# Automatically generated by qmake (1.02a) Tue Jul 16 20:59:39 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += mythepg menutest mythfilldatabase mythtv mythfrontend
