package ndfdXML;

# Generated by SOAP::Lite (v1.27) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Tue Jul 21 12:18:15 2026]
# -- generated from http://www.weather.gov/forecasts/xml/DWMLgen/wsdl/ndfdXML.wsdl
my %methods = (
'CornerPoints' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#CornerPoints',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'listType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'sector', type => 'tns:sectorType', attr => {}),
    ], # end parameters
  }, # end CornerPoints
'LatLonListLine' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#LatLonListLine',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'listType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'endPoint1Lat', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'endPoint1Lon', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'endPoint2Lat', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'endPoint2Lon', type => 'xsd:decimal', attr => {}),
    ], # end parameters
  }, # end LatLonListLine
'LatLonListSubgrid' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#LatLonListSubgrid',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'listType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lowerLeftLatitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'lowerLeftLongitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'upperRightLatitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'upperRightLongitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'resolution', type => 'xsd:decimal', attr => {}),
    ], # end parameters
  }, # end LatLonListSubgrid
'GmlTimeSeries' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#GmlTimeSeries',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'listLatLon', type => 'tns:listLatLonType', attr => {}),
      SOAP::Data->new(name => 'startTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'endTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'compType', type => 'tns:compTypeType', attr => {}),
      SOAP::Data->new(name => 'featureType', type => 'tns:featureTypeType', attr => {}),
      SOAP::Data->new(name => 'propertyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end GmlTimeSeries
'LatLonListZipCode' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#LatLonListZipCode',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'zipCodeList', type => 'tns:zipCodeListType', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'listType', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end LatLonListZipCode
'NDFDgenByDay' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#NDFDgenByDay',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'latitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'longitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'startDate', type => 'xsd:date', attr => {}),
      SOAP::Data->new(name => 'numDays', type => 'xsd:integer', attr => {}),
      SOAP::Data->new(name => 'Unit', type => 'tns:unitType', attr => {}),
      SOAP::Data->new(name => 'format', type => 'tns:formatType', attr => {}),
    ], # end parameters
  }, # end NDFDgenByDay
'LatLonListCityNames' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#LatLonListCityNames',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'displayLevel', type => 'tns:displayLevelType', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end LatLonListCityNames
'LatLonListSquare' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#LatLonListSquare',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'listType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'centerPointLat', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'centerPointLon', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'distanceLat', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'distanceLon', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'resolution', type => 'xsd:decimal', attr => {}),
    ], # end parameters
  }, # end LatLonListSquare
'GmlLatLonList' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#GmlLatLonList',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'listLatLon', type => 'tns:listLatLonType', attr => {}),
      SOAP::Data->new(name => 'requestedTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'featureType', type => 'tns:featureTypeType', attr => {}),
      SOAP::Data->new(name => 'weatherParameters', type => 'tns:weatherParametersType', attr => {}),
    ], # end parameters
  }, # end GmlLatLonList
'NDFDgenLatLonList' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#NDFDgenLatLonList',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'listLatLon', type => 'tns:listLatLonType', attr => {}),
      SOAP::Data->new(name => 'product', type => 'tns:productType', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'startTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'endTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'Unit', type => 'tns:unitType', attr => {}),
      SOAP::Data->new(name => 'weatherParameters', type => 'tns:weatherParametersType', attr => {}),
    ], # end parameters
  }, # end NDFDgenLatLonList
'NDFDgen' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#NDFDgen',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'latitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'longitude', type => 'xsd:decimal', attr => {}),
      SOAP::Data->new(name => 'product', type => 'tns:productType', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'startTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'endTime', type => 'xsd:dateTime', attr => {}),
      SOAP::Data->new(name => 'Unit', type => 'tns:unitType', attr => {}),
      SOAP::Data->new(name => 'weatherParameters', type => 'tns:weatherParametersType', attr => {}),
    ], # end parameters
  }, # end NDFDgen
'NDFDgenByDayLatLonList' => {
    endpoint => 'https://digital.weather.gov/xml/SOAP_server/ndfdXMLserver.php',
    soapaction => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl#NDFDgenByDayLatLonList',
    namespace => 'https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl',
    parameters => [
      SOAP::Data->new(name => 'listLatLon', type => 'tns:listLatLonType', attr => {}),
      SOAP::Data->new(name => 'XMLformat', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'startDate', type => 'xsd:date', attr => {}),
      SOAP::Data->new(name => 'numDays', type => 'xsd:integer', attr => {}),
      SOAP::Data->new(name => 'Unit', type => 'tns:unitType', attr => {}),
      SOAP::Data->new(name => 'format', type => 'tns:formatType', attr => {}),
    ], # end parameters
  }, # end NDFDgenByDayLatLonList
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
  $self->serializer->register_ns("https://digital.weather.gov/xml/wsdl/ndfdXML.wsdl","tns");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema-instance","xsi");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xsd");
  $self->serializer->register_ns("http://soapinterop.org/xsd","si");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/soap/envelope/","SOAP-ENV");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/soap/encoding/","SOAP-ENC");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/","wsdl");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;