#!/usr/bin/perl -w
#
# $Date$
# $Revision$
# $Author$
#
#   nuvinfo.pl

# Add a couple of include paths so we can load the various export and gui modules
    use File::Basename;
    use lib dirname($ENV{'_'}), '/usr/share/nuvexport', '/usr/local/share/nuvexport';

# Load the nuv utilities
    use mythtv::nuvinfo;

# No file specified?
    die "usage:\n\n   nuvinfo /path/to/file.nuv\n\n" unless ($ARGV[0]);

# Get the info about the requested file
    my $file = $ARGV[0];
    my %info = nuv_info($file);

# Print the info
    print "\ninfo for: $file\n\n";
    foreach $key (sort keys %info) {
        next unless ($key && defined $info{$key});
        print ' ' x (23 - length($key)) if (length($key) < 23);
        print "$key:  $info{$key}\n";
    }
    print "\ndone\n\n";



