######################################################################
# Automatically generated by qmake (1.03a) Wed Sep 25 13:43:31 2002
######################################################################

TEMPLATE = app
CONFIG -= moc
CONFIG += thread

include ( ../settings.pro )

INCLUDEPATH += ../libs/
LIBS += -lmyth-$$LIBVERSION -lXinerama -L../libs/libmyth -L/usr/local/lib

# Input
SOURCES += main.cpp
