#
#    Automatically generated by configure - modify only under penalty of death
#
 
#    The dummy plugin is always built 
 
SUBDIRS += ./mfd/plugins/dummy 
 
#    Build the zeroconfig plugin 
 
SUBDIRS += ./mfd/plugins/zeroconfig 
 
SUBDIRS += ./mfd/plugins/audio 
SUBDIRS += ./mfd/plugins/daapserver/daaplib 
SUBDIRS += ./mfd/plugins/daapserver/httpd_persistent 
SUBDIRS += ./mfd/plugins/daapserver 
