# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./i18n
# Target is an application:  

INSTALLS += trans 
trans.files = 

SOURCES += dummy.c 
