######################################################################
# Automatically generated by qmake (1.02a) Mon Jul 8 22:32:30 2002
######################################################################

TEMPLATE = app
CONFIG += thread
TARGET = menutest

include ( ../../settings.pro )

INCLUDEPATH += ../../libs/libmyth
LIBS += -lmyth-$$LIBVERSION -L/usr/local/lib -L../../libs/libmyth

# Input
SOURCES += main.cpp
