######################################################################
# Automatically generated by qmake (1.02a) Mon Jul 8 22:32:30 2002
######################################################################

TEMPLATE = app
CONFIG += thread
TARGET = menutest

include ( ../settings.pro )

themes.path = /usr/local/share/mythtv/themes/
themes.files = blue liquid

INSTALLS += themes

INCLUDEPATH += ../libmyth
LIBS += -lmyth -L/usr/local/lib -L../libmyth

# Input
SOURCES += main.cpp
