#
#    Automatically generated by configure - modify only under penalty of death
#
HEADERS += dvdripbox.h   dvdinfo.h   titledialog.h
SOURCES += dvdripbox.cpp dvdinfo.cpp titledialog.cpp
LIBS    += -ldvdread
