#
#    Automatically generated by configure - modify only under penalty of death
#
HEADERS += logging.h   mtd.h   serversocket.h   jobthread.h   dvdprobe.h
SOURCES += logging.cpp mtd.cpp serversocket.cpp jobthread.cpp dvdprobe.cpp
LIBS    += -ldvdread
