######################################################################
# Automatically generated by qmake (1.02a) Wed Jul 31 01:54:30 2002
######################################################################

TEMPLATE = subdirs

include (config.pro)

!exists( config.pro ) {
   error(Missing config.pro: please run the configure script)
}

# Directories
SUBDIRS += mythgallery theme i18n

