//////////////////////////////////////////////////////////////////////////////
// Program Name: v2resStats.h
// Created     : Oct. 18, 2021
//
// Copyright (c) 2026 Peter Bennett <pbennett@mythtv.org>
//
// Licensed under the GPL v2 or later, see COPYING for details
//
//////////////////////////////////////////////////////////////////////////////

#ifndef V2RECSTATS_H_
#define V2RECSTATS_H_

#include <QDateTime>
#include <QString>
#include <QVariantList>

#include "libmythbase/http/mythhttpservice.h"


class V2ShowStats : public QObject
{
    Q_OBJECT
    Q_CLASSINFO( "Version", "1.0" );
    SERVICE_PROPERTY2(QString, Title)
    SERVICE_PROPERTY2(int, Count)
    SERVICE_PROPERTY2(QDateTime, LastRecDate)
    public:
        Q_INVOKABLE V2ShowStats(QObject *parent = nullptr)
            : QObject( parent )
        {
        }
    private:
        Q_DISABLE_COPY(V2ShowStats);
};
Q_DECLARE_METATYPE(V2ShowStats*)


class V2RecStats : public QObject
{
    Q_OBJECT
    Q_CLASSINFO( "Version", "1.0" );

    Q_CLASSINFO( "Shows", "type=V2ShowStats")
    Q_CLASSINFO( "Channels", "type=V2ShowStats")

    SERVICE_PROPERTY2(int, ShowCount)
    SERVICE_PROPERTY2(int, EpisodeCount)
    SERVICE_PROPERTY2(QDateTime, FirstRecDate)
    SERVICE_PROPERTY2(QDateTime, LastRecDate)
    SERVICE_PROPERTY2(long long, RunTimeSecs)
    SERVICE_PROPERTY2(long long, RecTimeSecs)
    SERVICE_PROPERTY2( QVariantList, Shows )
    SERVICE_PROPERTY2( QVariantList, Channels )

    public:
        Q_INVOKABLE V2RecStats(QObject *parent = nullptr)
            : QObject(parent)
        {
        }
        // These are here so that a routine in serviceutil
        // can fill the QVariantlist. Unfortunately the standard
        // call [e.g. GetShows()] generated by the macros returns a
        // const QVariantlist.
        QVariantList& GetShows() {return m_Shows;}
        QVariantList& GetChannels() {return m_Channels;}

        V2ShowStats *AddNewShow()
        {
            // We must make sure the object added to the QVariantList has
            // a parent of 'this'
            auto *pObject = new V2ShowStats( this );
            m_Shows.append( QVariant::fromValue<QObject *>( pObject ));
            return pObject;
        }

        V2ShowStats *AddNewChannel()
        {
            // We must make sure the object added to the QVariantList has
            // a parent of 'this'
            auto *pObject = new V2ShowStats( this );
            m_Channels.append( QVariant::fromValue<QObject *>( pObject ));
            return pObject;
        }

    private:
        Q_DISABLE_COPY(V2RecStats);
};
Q_DECLARE_METATYPE(V2RecStats*)

#endif // V2RECSTATS_H_
