######################################################################
# Automatically generated by qmake (1.03a) Fri Aug 23 14:59:03 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += invert linearblend denoise3d
