######################################################################
# Automatically generated by qmake (1.02a) Wed Jul 31 01:54:30 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS = mythdvd mtd i18n
