#!/usr/bin/perl -w
    
use strict;

use DBI;
my %settings = ();
my $settingsfile = "../mythfrontend/mysql.txt";
if (open(FOO, $settingsfile)) {
    while (<FOO>) {
        chomp;
        if (/str (.*?)=(.*)/) {
            $settings{$1} = $2;
        }
    }

    close FOO;
}

$settingsfile = "/usr/local/share/mythtv/mysql.txt";
if (open(FOO, $settingsfile)) {
    while (<FOO>) {
        chomp;
        if (/str (.*?)=(.*)/) {
            $settings{$1} = $2;
        }
    }

    close FOO;
}

$settingsfile = $ENV{"HOME"} . "/.mythtv/mysql.txt";
if (open(FOO, $settingsfile)) {
    while (<FOO>) {
        chomp;
        if (/str (.*?)=(.*)/) {
            $settings{$1} = $2;
        }
    }

    close FOO;
}

my $dbstr = "DBI:mysql:database=" . $settings{"DBName"} . ":host=" . 
            $settings{"DBHostName"};

my $dbh = DBI->connect($dbstr, $settings{"DBUserName"}, 
                       $settings{"DBPassword"}, { PrintError => 0 } )
   or die DBI->errstr;

my $offset;

system("./grabdata 1");

# Yes, this looks weird -- the 0 and 1 cases will normally never be used.
# Basically, it just checks to see if today has data (in the case of this
# being the first ever run)
for ($offset = 0; $offset < 9; $offset++)
{
    my $nextoffset = $offset + 1;
    my $sth = $dbh->prepare("SELECT * FROM program WHERE starttime >= DATE_ADD(CURRENT_DATE, INTERVAL $offset DAY) AND starttime < DATE_ADD(CURRENT_DATE, INTERVAL $nextoffset DAY);");
    $sth->execute() or die $sth->errstr;

    if ($sth->rows == 0)
    {
        system("./grabdata $offset");
    }
}

$dbh->do("DELETE FROM program WHERE starttime <= DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY)")
   or die $dbh->errstr;
