######################################################################
# Automatically generated by qmake (1.03a) Fri Aug 23 15:01:33 2002
######################################################################

TEMPLATE = lib
CONFIG -= moc
CONFIG += plugin
target.path = /usr/local/lib/mythtv/filters
INSTALLS = target

INCLUDEPATH += ../../libNuppelVideo

QMAKE_CFLAGS_RELEASE += -Wno-missing-prototypes
QMAKE_CFLAGS_DEBUG += -Wno-missing-prototypes

# Input
SOURCES += filter_invert.c
