#!/bin/sh
#
# cpsvndir: recursive directory copy excluding .svn sub dirs.

DESTDIR=$2
SOURCE=$1

mkdir -p $DESTDIR/$SOURCE || exit 1

find $SOURCE -path '*/.svn' -prune -or -type d -exec mkdir -p $DESTDIR/{} \;
find $SOURCE -path '*/.svn' -prune -or -type f -exec cp {} $DESTDIR/{} \;


exit 0

