######################################################################
# Automatically generated by qmake (1.03a) Sat Sep 21 15:30:26 2002
######################################################################

include ( ../settings.pro )

TEMPLATE = app
CONFIG -= moc qt

themes.path = $${PREFIX}/share/mythtv/themes/
themes.files = blue liquid defaultosd

INSTALLS += themes 

# Input
SOURCES += dummy.c
