void strings_null() {
    ThemeUI::tr("1. General");
    ThemeUI::tr("2. Capture cards");
    ThemeUI::tr("3. Video sources");
    ThemeUI::tr("4. Input connections");
    ThemeUI::tr("5. Channel Editor");
    ThemeUI::tr("6. Storage Directories");
    ThemeUI::tr("%alert_text%");
    ThemeUI::tr("LINE #%caller_line%");
    ThemeUI::tr("NAME: %caller_name%");
    ThemeUI::tr("NUM : %caller_number%");
    ThemeUI::tr("DATE: %caller_date% TIME : %caller_time%");
    ThemeUI::tr("Welcome to MythTV");
    ThemeUI::tr("MythTV is idle and will shutdown shortly.");
    ThemeUI::tr("Current Recording(s)");
    ThemeUI::tr("Retrieving Recording Status ...");
    ThemeUI::tr("Next Scheduled Recording(s)");
    ThemeUI::tr("Retrieving Scheduled Recordings ...");
    ThemeUI::tr("WARNING: There are conflicting scheduled recordings!");
    ThemeUI::tr("General");
    ThemeUI::tr("Core MythTV behavior and system settings");
    ThemeUI::tr("Appearance");
    ThemeUI::tr("pick the theme, font, size, and locale");
    ThemeUI::tr("Screen Setup Wizards");
    ThemeUI::tr("Compensate for TVs with overscan");
    ThemeUI::tr("TV Settings");
    ThemeUI::tr("Settings for TV recording and playback");
    ThemeUI::tr("Music Settings");
    ThemeUI::tr("Configure playback and CD ripping");
    ThemeUI::tr("Videos Settings");
    ThemeUI::tr("Configure playback and DVD ripping");
    ThemeUI::tr("Radio Settings");
    ThemeUI::tr("Images Settings");
    ThemeUI::tr("Configure display of image gallery");
    ThemeUI::tr("Game Settings");
    ThemeUI::tr("Configure playback of games");
    ThemeUI::tr("Weather Settings");
    ThemeUI::tr("Weather locale and sources");
    ThemeUI::tr("News Settings");
    ThemeUI::tr("Choose which news sources interest you");
    ThemeUI::tr("Web Settings");
    ThemeUI::tr("Manage web bookmarks");
    ThemeUI::tr("Recipe Settings");
    ThemeUI::tr("Phone Settings");
    ThemeUI::tr("Configure SIP-based VoIP phone");
    ThemeUI::tr("Movie Time Settings");
    ThemeUI::tr("Select local movie theaters");
    ThemeUI::tr("Xbox Settings");
    ThemeUI::tr("NetFlix Settings");
    ThemeUI::tr("Choose the genres that interest you");
    ThemeUI::tr("Archive Files Settings");
    ThemeUI::tr("Configure how to archive video to DVD");
    ThemeUI::tr("ZoneMinder Settings");
    ThemeUI::tr("Set up surveillance software");
    ThemeUI::tr("Watch Recordings");
    ThemeUI::tr("Play Recordings");
    ThemeUI::tr("Upcoming Recordings");
    ThemeUI::tr("See what will be recorded next");
    ThemeUI::tr("Schedule Recordings");
    ThemeUI::tr("Pick shows to record");
    ThemeUI::tr("Recording Priorities");
    ThemeUI::tr("Prioritize some shows over others");
    ThemeUI::tr("System Status");
    ThemeUI::tr("What your system is doing right now");
    ThemeUI::tr("Utilities / Setup");
    ThemeUI::tr("Settings for TV, Images, Music, Video, Weather, etc.");
    ThemeUI::tr("Set Recording Priorities");
    ThemeUI::tr("Settings to prioritize some shows over others");
    ThemeUI::tr("Set Channel Recording Priorities");
    ThemeUI::tr("Settings to prioritize some channels over others");
    ThemeUI::tr("Custom Priority");
    ThemeUI::tr("Most used DVR options are found on the main menu. Plugin options are in the utilities menu.");
    ThemeUI::tr("New Titles");
    ThemeUI::tr("Pick a program to record for a list of new titles");
    ThemeUI::tr("Movies");
    ThemeUI::tr("Pick a movie to record");
    ThemeUI::tr("Categories");
    ThemeUI::tr("Pick a program based on category");
    ThemeUI::tr("Channels");
    ThemeUI::tr("Pick a program on a given channel");
    ThemeUI::tr("Time");
    ThemeUI::tr("Pick a program based on time");
    ThemeUI::tr("Program Guide");
    ThemeUI::tr("Choose programs from a grid-style list");
    ThemeUI::tr("Program Finder");
    ThemeUI::tr("Choose programs from an alphabetical index");
    ThemeUI::tr("Search Words");
    ThemeUI::tr("Find programs matching search words");
    ThemeUI::tr("Search Lists");
    ThemeUI::tr("Pick a program to record from a set of lists");
    ThemeUI::tr("Custom Record");
    ThemeUI::tr("Advanced program finder");
    ThemeUI::tr("Manual Schedule");
    ThemeUI::tr("VCR-like recording scheduler");
    ThemeUI::tr("Titles");
    ThemeUI::tr("Find a program based on title");
    ThemeUI::tr("Keywords");
    ThemeUI::tr("Find a program matching a keyword");
    ThemeUI::tr("People");
    ThemeUI::tr("Find a program including a given person");
    ThemeUI::tr("Advanced");
    ThemeUI::tr("Combine more than one word search");
    ThemeUI::tr("Stored Searches");
    ThemeUI::tr("Results of searches you have saved");
    ThemeUI::tr("TV navigation and recording preferences");
    ThemeUI::tr("Guide appearance and behavior");
    ThemeUI::tr("Playback");
    ThemeUI::tr("Settings for viewing and playing TV");
    ThemeUI::tr("Playback OSD");
    ThemeUI::tr("Theme and settings for OSD");
    ThemeUI::tr("OSD Menu Editor");
    ThemeUI::tr("Playback Groups");
    ThemeUI::tr("Adjust settings for different playback styles");
    ThemeUI::tr("Channel Groups");
    ThemeUI::tr("Recording Profiles");
    ThemeUI::tr("Global recording priority and scheduling");
    ThemeUI::tr("Watch TV");
    ThemeUI::tr("Watch live television");
    ThemeUI::tr("Delete Recordings");
    ThemeUI::tr("Remove television recordings");
    ThemeUI::tr("Previously Recorded");
    ThemeUI::tr("See what you have recorded before");
    ThemeUI::tr("TV Utilities");
    ThemeUI::tr("Music");
    ThemeUI::tr("Videos");
    ThemeUI::tr("Radio");
    ThemeUI::tr("Images");
    ThemeUI::tr("Games");
    ThemeUI::tr("Weather");
    ThemeUI::tr("News Feeds");
    ThemeUI::tr("Web");
    ThemeUI::tr("Phone");
    ThemeUI::tr("Burn DVD");
    ThemeUI::tr("Recipes");
    ThemeUI::tr("Archive Files");
    ThemeUI::tr("Zone Minder");
    ThemeUI::tr("Movie Times");
    ThemeUI::tr("NetFlix");
    ThemeUI::tr("Edit Keys");
    ThemeUI::tr("Setup");
    ThemeUI::tr("A blue theme.");
    ThemeUI::tr("%SUBTITLE|\"|\"%");
    ThemeUI::tr("%STARS%%DESCRIPTION%");
    ThemeUI::tr("Scheduled Recordings:");
    ThemeUI::tr("(1) All  (2) Important");
    ThemeUI::tr("Showing:");
    ThemeUI::tr("%SUBTITLE|\"|\" %%STARS%%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded");
    ThemeUI::tr("To schedule a recording, exit this screen and");
    ThemeUI::tr("Select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("Preview Schedule Changes:");
    ThemeUI::tr("The recording schedule would not be affected.");
    ThemeUI::tr("Channel Recording Priorities");
    ThemeUI::tr("(1) Channel    (2) Priority");
    ThemeUI::tr("Source:");
    ThemeUI::tr("Priority:");
    ThemeUI::tr("Program Recording Priorities");
    ThemeUI::tr("Priority");
    ThemeUI::tr("Final Priority");
    ThemeUI::tr("(1) Title    (2) Priority    (4) Type");
    ThemeUI::tr("Record Type:");
    ThemeUI::tr("[");
    ThemeUI::tr("]");
    ThemeUI::tr("]  =");
    ThemeUI::tr("Select a recording to permanently erase:");
    ThemeUI::tr("Select a recording to watch:");
    ThemeUI::tr("Sorry, No Recordings Available");
    ThemeUI::tr("Select 'Schedule a Recording' from the Main Menu");
    ThemeUI::tr("(4) Program Guide   **(6) Program Finder **");
    ThemeUI::tr("Select a letter...");
    ThemeUI::tr("Pick the letter in which the show starts with, then press SELECT or the right arrow");
    ThemeUI::tr("Select a program...");
    ThemeUI::tr("Select the title of the program you wish to find. When finished return with the left arrow key. Press SELECT to schedule a recording.");
    ThemeUI::tr("No Programs");
    ThemeUI::tr("There are no available programs under this search. Please select another search.");
    ThemeUI::tr("Program Listings");
    ThemeUI::tr("(1)Time (2)Title");
    ThemeUI::tr("No listings found for this program.");
    ThemeUI::tr("Airdate:");
    ThemeUI::tr("Channel:");
    ThemeUI::tr("Description:");
    ThemeUI::tr("Show:  (1) All  (2) Important");
    ThemeUI::tr("(1) Sort by Title  (2) Sort by Priority  (4) Sort by Type");
    ThemeUI::tr("] =");
    ThemeUI::tr("%SUBTITLE|\"|\"% %STARS%%DESCRIPTION%");
    ThemeUI::tr("(4) Program Guide  (6) Program Finder");
    ThemeUI::tr("Select a letter.");
    ThemeUI::tr("Pick the letter in which the show starts with, then press SELECT or the right arrow.");
    ThemeUI::tr("Select a program.");
    ThemeUI::tr("No Programs.");
    ThemeUI::tr("(1) Sort by Time    (2) Sort by Title");
    ThemeUI::tr("Heading");
    ThemeUI::tr("Cancel");
    ThemeUI::tr("Ok");
    ThemeUI::tr("0%");
    ThemeUI::tr("Playback starting ...");
    ThemeUI::tr("Icon Importer");
    ThemeUI::tr("Search terms:");
    ThemeUI::tr("Search");
    ThemeUI::tr("Skip");
    ThemeUI::tr("Channel Editor");
    ThemeUI::tr("List Options");
    ThemeUI::tr("Sort By:");
    ThemeUI::tr("Hide Channels without channel number.");
    ThemeUI::tr("Delete All");
    ThemeUI::tr("Global Options");
    ThemeUI::tr("Channel Scan");
    ThemeUI::tr("Icon Download");
    ThemeUI::tr("Edit Transports");
    ThemeUI::tr("Done");
    ThemeUI::tr("Play Games");
    ThemeUI::tr("System:");
    ThemeUI::tr("Year:");
    ThemeUI::tr("Genre:");
    ThemeUI::tr("Favorite:");
    ThemeUI::tr("Yes");
    ThemeUI::tr("No");
    ThemeUI::tr("Television");
    ThemeUI::tr("Main Menu");
    ThemeUI::tr("Gallery");
    ThemeUI::tr("Schedule");
    ThemeUI::tr("Programme Searches");
    ThemeUI::tr("CD/DVD Options");
    ThemeUI::tr("Media Library");
    ThemeUI::tr("Info Centre");
    ThemeUI::tr("P");
    ThemeUI::tr("S");
    ThemeUI::tr("Playing:");
    ThemeUI::tr("None");
    ThemeUI::tr("%|\"SUBTITLE|\"% %DESCRIPTION%");
    ThemeUI::tr("Change Displayed Groups");
    ThemeUI::tr("Show Titles");
    ThemeUI::tr("Show Categories");
    ThemeUI::tr("Show Recording Groups");
    ThemeUI::tr("Show Watch List");
    ThemeUI::tr("Show Searches");
    ThemeUI::tr("Show LiveTV");
    ThemeUI::tr("Show Watched Recordings");
    ThemeUI::tr("Save");
    ThemeUI::tr("Change Recording Group Password");
    ThemeUI::tr("Old Password");
    ThemeUI::tr("New Password:");
    ThemeUI::tr("OK");
    ThemeUI::tr("Edit Recording Metadata");
    ThemeUI::tr("Title");
    ThemeUI::tr("Subtitle");
    ThemeUI::tr("Manual Recording Schedule");
    ThemeUI::tr("Title (Optional):");
    ThemeUI::tr("Date, or day of week:");
    ThemeUI::tr("Start Time:");
    ThemeUI::tr("Hour");
    ThemeUI::tr("Minute");
    ThemeUI::tr("Duration:");
    ThemeUI::tr("Next");
    ThemeUI::tr("Scheduled Recordings");
    ThemeUI::tr("Schedules Overview");
    ThemeUI::tr("First Conflict:");
    ThemeUI::tr("Filter:");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and Select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("Callsign:");
    ThemeUI::tr("(1) Channel (2) Priority");
    ThemeUI::tr("Schedule Priorities");
    ThemeUI::tr("Final");
    ThemeUI::tr("Type Priority:");
    ThemeUI::tr("Final Priority:");
    ThemeUI::tr("(1) Title (2) Priority (4) Type");
    ThemeUI::tr("Custom Priority Rules");
    ThemeUI::tr("Existing Rules:");
    ThemeUI::tr("Rule Name:");
    ThemeUI::tr("Priority Change:");
    ThemeUI::tr("Select a clause from the list.");
    ThemeUI::tr("Add Clause");
    ThemeUI::tr("Delete");
    ThemeUI::tr("Test");
    ThemeUI::tr("Install");
    ThemeUI::tr("Phrase");
    ThemeUI::tr("Select Time");
    ThemeUI::tr("Select Search");
    ThemeUI::tr("Edit Power Search Fields");
    ThemeUI::tr("Optional title phrase:");
    ThemeUI::tr("Optional subtitle phrase:");
    ThemeUI::tr("Optional description phrase:");
    ThemeUI::tr("List Overview");
    ThemeUI::tr("Current View:");
    ThemeUI::tr("Position:");
    ThemeUI::tr("Program Details");
    ThemeUI::tr("Schedule Editor");
    ThemeUI::tr("Rule Overview");
    ThemeUI::tr("Select the recording rule");
    ThemeUI::tr("Schedule Options");
    ThemeUI::tr("Storage Options");
    ThemeUI::tr("Post Processing");
    ThemeUI::tr("Schedule Info");
    ThemeUI::tr("Preview");
    ThemeUI::tr("Reduce priority by %n", 0, 1);
    ThemeUI::tr("Normal recording priority");
    ThemeUI::tr("Raise priority by %n", 0, 1);
    ThemeUI::tr("Start recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Start recording on time");
    ThemeUI::tr("Start recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording on time");
    ThemeUI::tr("End recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Recording Rule Active");
    ThemeUI::tr("Back");
    ThemeUI::tr("No episode limit");
    ThemeUI::tr("Keep at most %n episode(s)", 0, 1);
    ThemeUI::tr("Allow recordings to expire?");
    ThemeUI::tr("Post-Processing Options");
    ThemeUI::tr("Commercial Flag new recordings");
    ThemeUI::tr("Transcode new recordings");
    ThemeUI::tr("123");
    ThemeUI::tr("Search For:");
    ThemeUI::tr("%SUBTITLE|\"|\" %%REPEAT%%STARS%%DESCRIPTION%");
    ThemeUI::tr("Search Results");
    ThemeUI::tr("Cast Members");
    ThemeUI::tr("Full Plot");
    ThemeUI::tr("Video List Filters");
    ThemeUI::tr("Text Filter:");
    ThemeUI::tr("Category");
    ThemeUI::tr("Genre");
    ThemeUI::tr("Country");
    ThemeUI::tr("Actor/Actress");
    ThemeUI::tr("Year");
    ThemeUI::tr("Runtime");
    ThemeUI::tr("User Rating");
    ThemeUI::tr("Browse");
    ThemeUI::tr("InetRef");
    ThemeUI::tr("Cover File");
    ThemeUI::tr("Sort by");
    ThemeUI::tr("Watched");
    ThemeUI::tr("Make default");
    ThemeUI::tr("Video Manager");
    ThemeUI::tr("Director:");
    ThemeUI::tr("Parental:");
    ThemeUI::tr("Lowest");
    ThemeUI::tr("Low");
    ThemeUI::tr("Medium");
    ThemeUI::tr("High");
    ThemeUI::tr("Rated:");
    ThemeUI::tr("Browsable:");
    ThemeUI::tr("Runtime:");
    ThemeUI::tr("Filename:");
    ThemeUI::tr("Cover File:");
    ThemeUI::tr("IMDB ID:");
    ThemeUI::tr("Video Browser");
    ThemeUI::tr("Videos - Gallery");
    ThemeUI::tr("Videos - Tree");
    ThemeUI::tr("Parental Level");
    ThemeUI::tr("Video File Associations");
    ThemeUI::tr("Extension:");
    ThemeUI::tr("Command:");
    ThemeUI::tr("Use default player:");
    ThemeUI::tr("Ignore:");
    ThemeUI::tr("Edit Video Metadata");
    ThemeUI::tr("Title:");
    ThemeUI::tr("Subtitle:");
    ThemeUI::tr("Season:");
    ThemeUI::tr("Episode:");
    ThemeUI::tr("Category:");
    ThemeUI::tr("Parental Control:");
    ThemeUI::tr("File to Always Play Next:");
    ThemeUI::tr("Include while Browsing:");
    ThemeUI::tr("Item has been Watched:");
    ThemeUI::tr("Cover Art:");
    ThemeUI::tr("Screenshot:");
    ThemeUI::tr("Banner:");
    ThemeUI::tr("Fanart:");
    ThemeUI::tr("Trailer:");
    ThemeUI::tr("Unique Player Command:");
    ThemeUI::tr("Directed by:");
    ThemeUI::tr("Play");
    ThemeUI::tr("Change mythtv key bindings.");
    ThemeUI::tr("MythStream Settings");
    ThemeUI::tr("Weather Station Settings");
    ThemeUI::tr("TV");
    ThemeUI::tr("Play Online Streams");
    ThemeUI::tr("Weather Station");
    ThemeUI::tr("A long menu which breaks down the options by their category. TV, Music, Video etc");
    ThemeUI::tr("Search Listings");
    ThemeUI::tr("Recording Rules");
    ThemeUI::tr("Edit or delete any recording rule");
    ThemeUI::tr("Play TV Recordings");
    ThemeUI::tr("Appearance Wizard");
    ThemeUI::tr("Move the selected arrow to the corner of the TV screen.  Press SELECT to edit the other arrow.  Press MENU for options and ESC to quit.");
    ThemeUI::tr("1280 x 720");
    ThemeUI::tr("0 x 0");
    ThemeUI::tr("1 pixel");
    ThemeUI::tr("Up Level");
    ThemeUI::tr("Home");
    ThemeUI::tr("Please Wait....");
    ThemeUI::tr("Sort Mode:");
    ThemeUI::tr("Video Source:");
    ThemeUI::tr("Contexts");
    ThemeUI::tr("Actions");
    ThemeUI::tr("%|\"SUBTITLE|\"% %STARS% %DESCRIPTION%");
    ThemeUI::tr("Change View");
    ThemeUI::tr("Show Watched Programs");
    ThemeUI::tr("Old Password:");
    ThemeUI::tr("Status Icons");
    ThemeUI::tr("%LONGREPEAT%%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("Manage Recording Rules");
    ThemeUI::tr("Channel");
    ThemeUI::tr("Last Recorded");
    ThemeUI::tr("Recording Group:");
    ThemeUI::tr("Storage Group:");
    ThemeUI::tr("Recording Profile:");
    ThemeUI::tr("Program Details:");
    ThemeUI::tr("Enter Search Text");
    ThemeUI::tr("Close");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("Custom Record Rules");
    ThemeUI::tr("Additional Tables:");
    ThemeUI::tr("Record");
    ThemeUI::tr("Store");
    ThemeUI::tr("%|\"SUBTITLE|\"% %LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("Details");
    ThemeUI::tr("This screen displays the status of various system components");
    ThemeUI::tr("Run User Job #1");
    ThemeUI::tr("Run User job #2");
    ThemeUI::tr("Run User Job #3");
    ThemeUI::tr("Run User Job #4");
    ThemeUI::tr("Make or accept a VoIP call");
    ThemeUI::tr("Keep up with the news");
    ThemeUI::tr("See when local movies are playing");
    ThemeUI::tr("Local weather forecast");
    ThemeUI::tr("Manage your NetFlix queue");
    ThemeUI::tr("Browse the web");
    ThemeUI::tr("Start cooking!");
    ThemeUI::tr("Home surveillance");
    ThemeUI::tr("Hardware profile");
    ThemeUI::tr("Tell us what hardware you have so we can support it");
    ThemeUI::tr("Play recordings");
    ThemeUI::tr("Watch Videos");
    ThemeUI::tr("Play videos");
    ThemeUI::tr("Listen to Music");
    ThemeUI::tr("Listen to the radio");
    ThemeUI::tr("Image Gallery");
    ThemeUI::tr("Look at Pictures");
    ThemeUI::tr("Play video games");
    ThemeUI::tr("Media Settings");
    ThemeUI::tr("Settings for all non-TV media");
    ThemeUI::tr("Info Center Settings");
    ThemeUI::tr("Configure weather, news, movie info, web, and recipes");
    ThemeUI::tr("Play any of your media");
    ThemeUI::tr("Manage Recordings");
    ThemeUI::tr("Pick and prioritize shows to record");
    ThemeUI::tr("Information Center");
    ThemeUI::tr("Information and Communications");
    ThemeUI::tr("Optical Disks");
    ThemeUI::tr("Play or import CDs and DVDs");
    ThemeUI::tr("Configure MythTV and plugins");
    ThemeUI::tr("Set Priorities");
    ThemeUI::tr("Play DVD");
    ThemeUI::tr("Play the video on a movie DVD");
    ThemeUI::tr("Play VCD");
    ThemeUI::tr("Play the video on a VCD");
    ThemeUI::tr("Import DVD");
    ThemeUI::tr("Import video from a movie DVD");
    ThemeUI::tr("Write video to a data DVD");
    ThemeUI::tr("Import CD");
    ThemeUI::tr("Import music from an audio CD");
    ThemeUI::tr("Eject media");
    ThemeUI::tr("Eject CD or DVD from drive");
    ThemeUI::tr("Music Tools");
    ThemeUI::tr("Select, import, or play music");
    ThemeUI::tr("Scan for new videos, edit metadata, or delete");
    ThemeUI::tr("%SUBTITLE%%BR%%DESCRIPTION%");
    ThemeUI::tr("%DESCRIPTION%");
    ThemeUI::tr("%STARTDATE%");
    ThemeUI::tr("Callsign");
    ThemeUI::tr("Channel #");
    ThemeUI::tr("Channel Name");
    ThemeUI::tr("XMLTV ID");
    ThemeUI::tr("[P]robe");
    ThemeUI::tr("[O]k");
    ThemeUI::tr("%DESCRIPTION%%BR%(%STARTTIME% - %LENMINS%)");
    ThemeUI::tr("%CALLSIGN% - %CHANNUM%");
    ThemeUI::tr("A simple transparent black and white theme.");
    ThemeUI::tr("Play or import audio or video CDs or DVDs");
    ThemeUI::tr("Watch A DVD");
    ThemeUI::tr("Watch Live TV");
    ThemeUI::tr("Watch Online Streams");
    ThemeUI::tr("Plugins");
    ThemeUI::tr("Other Plugins");
    ThemeUI::tr("Advanced Options");
    ThemeUI::tr("A \"Media Center\" menu theme. This menu theme is basically meant to bring the common \"media player/DVR\" functionality to the forefront, organize the plugins, and to make some of myth's more daunting options a little more subtle. Places the common media items on the top level (Recordings, Videos, TV, DVD, Music), places all informational plugins in \"Plugins.\" Puts all setup and scheduling in \"Advanced.\" The top two menu levels will seem new, the ones beneath Advanced->Setup are as in the default menu.");
}
