void strings_null() {
    ThemeUI::tr("A high quality profile giving approx. 1 hour of video on a single layer DVD");
    ThemeUI::tr("A standard play profile giving approx. 2 hour of video on a single layer DVD");
    ThemeUI::tr("A long play profile giving approx. 4 hour of video on a single layer DVD");
    ThemeUI::tr("A extended play profile giving approx. 6 hour of video on a single layer DVD");
    ThemeUI::tr("Select Destination");
    ThemeUI::tr("description goes here.");
    ThemeUI::tr("Find");
    ThemeUI::tr("Free Space:");
    ThemeUI::tr("0.00Gb");
    ThemeUI::tr("Make ISO Image");
    ThemeUI::tr("Burn to DVD");
    ThemeUI::tr("Force Overwrite of DVD-RW Media");
    ThemeUI::tr("Cancel");
    ThemeUI::tr("Prev");
    ThemeUI::tr("Next");
    ThemeUI::tr("Select Recordings");
    ThemeUI::tr("Show Recordings");
    ThemeUI::tr("OK");
    ThemeUI::tr("File Finder");
    ThemeUI::tr("Back");
    ThemeUI::tr("Home");
    ThemeUI::tr("Select Videos");
    ThemeUI::tr("Video Category");
    ThemeUI::tr("title goes here");
    ThemeUI::tr("x.xx Gb");
    ThemeUI::tr("PL:");
    ThemeUI::tr("1");
    ThemeUI::tr("No videos available");
    ThemeUI::tr("Log Viewer");
    ThemeUI::tr("Update");
    ThemeUI::tr("Exit");
    ThemeUI::tr("Change Encoding Profile");
    ThemeUI::tr("12.34 GB");
    ThemeUI::tr("DVD Menu Theme");
    ThemeUI::tr("Select a theme");
    ThemeUI::tr("Intro");
    ThemeUI::tr("Main Menu");
    ThemeUI::tr("Chapter Menu");
    ThemeUI::tr("Details");
    ThemeUI::tr("Select Archive Items");
    ThemeUI::tr("No files are selected for archive");
    ThemeUI::tr("Add Recording");
    ThemeUI::tr("Add Video");
    ThemeUI::tr("Add File");
    ThemeUI::tr("xxxxx MB");
    ThemeUI::tr("0 MB");
    ThemeUI::tr("Archive Item Details");
    ThemeUI::tr("Title:");
    ThemeUI::tr("Subtitle:");
    ThemeUI::tr("Start Date:");
    ThemeUI::tr("Time:");
    ThemeUI::tr("Description:");
    ThemeUI::tr("Thumb Image Selector");
    ThemeUI::tr("Current Position");
    ThemeUI::tr("0:00:00.00");
    ThemeUI::tr("Seek Amount");
    ThemeUI::tr("Frame");
    ThemeUI::tr("Save");
    ThemeUI::tr("sep 13, 2004 11:00 pm (1h 15m)");
    ThemeUI::tr("x.xx GB");
    ThemeUI::tr("File Finder To Import");
    ThemeUI::tr("Start Time:");
    ThemeUI::tr("Select Associated Channel");
    ThemeUI::tr("Archived Channel");
    ThemeUI::tr("Chan. ID:");
    ThemeUI::tr("Chan. No:");
    ThemeUI::tr("Callsign:");
    ThemeUI::tr("Name:");
    ThemeUI::tr("Local Channel");
    ThemeUI::tr("Search Channel");
    ThemeUI::tr("Search Callsign");
    ThemeUI::tr("Search Name");
    ThemeUI::tr("Finish");
    ThemeUI::tr("Add video");
    ThemeUI::tr("Create DVD");
    ThemeUI::tr("Create Archive");
    ThemeUI::tr("Encode Video File");
    ThemeUI::tr("Import Archive");
    ThemeUI::tr("Archive Utilities");
    ThemeUI::tr("Show Log Viewer");
    ThemeUI::tr("Play Created DVD");
    ThemeUI::tr("Burn DVD");
    ThemeUI::tr("Bookmark Manager");
    ThemeUI::tr("Category");
    ThemeUI::tr("[x]");
    ThemeUI::tr("Name");
    ThemeUI::tr("URL");
    ThemeUI::tr("Category:");
    ThemeUI::tr("Find...");
    ThemeUI::tr("URL:");
    ThemeUI::tr("Ok");
    ThemeUI::tr("Browser Command:");
    ThemeUI::tr("Text Size:");
    ThemeUI::tr("Games");
    ThemeUI::tr("System:");
    ThemeUI::tr("Year:");
    ThemeUI::tr("Genre:");
    ThemeUI::tr("Favorite:");
    ThemeUI::tr("No");
    ThemeUI::tr("Yes");
    ThemeUI::tr("Edit Game Information");
    ThemeUI::tr("Game Name:");
    ThemeUI::tr("Country:");
    ThemeUI::tr("Publisher:");
    ThemeUI::tr("Plot:");
    ThemeUI::tr("Screenshot:");
    ThemeUI::tr("Fanart:");
    ThemeUI::tr("Boxart:");
    ThemeUI::tr("/path/to/the/thing.jpg");
    ThemeUI::tr("Done");
    ThemeUI::tr("Game:");
    ThemeUI::tr("Type:");
    ThemeUI::tr("Filename:");
    ThemeUI::tr("Rompath:");
    ThemeUI::tr("System(s):");
    ThemeUI::tr("CRC:");
    ThemeUI::tr("No Plot.");
    ThemeUI::tr("Play");
    ThemeUI::tr("Game Information");
    ThemeUI::tr("General Settings");
    ThemeUI::tr("Game folders and general options");
    ThemeUI::tr("Game Players");
    ThemeUI::tr("Configure an emulator");
    ThemeUI::tr("Scan for Games");
    ThemeUI::tr("Add games to your library");
    ThemeUI::tr("Clear Game Data");
    ThemeUI::tr("Empty your game library");
    ThemeUI::tr("Please Wait...");
    ThemeUI::tr("Track Information");
    ThemeUI::tr("Compilation:");
    ThemeUI::tr("Comp. Artist:");
    ThemeUI::tr("Artist:");
    ThemeUI::tr("Album:");
    ThemeUI::tr("Track No.:");
    ThemeUI::tr("Rating:");
    ThemeUI::tr("Play Count:");
    ThemeUI::tr("Last Play:");
    ThemeUI::tr("Album Art");
    ThemeUI::tr("No Album Art Found");
    ThemeUI::tr("Metadata");
    ThemeUI::tr("Quality:");
    ThemeUI::tr("Multi-Artist:");
    ThemeUI::tr("Switch Titles");
    ThemeUI::tr("Track");
    ThemeUI::tr("Title");
    ThemeUI::tr("Artist");
    ThemeUI::tr("Length");
    ThemeUI::tr("Scan CD");
    ThemeUI::tr("Rip CD");
    ThemeUI::tr("Importing CD");
    ThemeUI::tr("Encoding Track");
    ThemeUI::tr("Import Music");
    ThemeUI::tr("Location:");
    ThemeUI::tr("Already in database");
    ThemeUI::tr("Search");
    ThemeUI::tr("Cover Art");
    ThemeUI::tr("Add");
    ThemeUI::tr("Next New");
    ThemeUI::tr("Add All New");
    ThemeUI::tr("Import Cover Art");
    ThemeUI::tr("File:");
    ThemeUI::tr("Destination:");
    ThemeUI::tr("Image Type:");
    ThemeUI::tr("Copy");
    ThemeUI::tr("Please Wait ...");
    ThemeUI::tr("Volume");
    ThemeUI::tr("0%");
    ThemeUI::tr("Length:");
    ThemeUI::tr("Last Played:");
    ThemeUI::tr("Last Value");
    ThemeUI::tr("Played:");
    ThemeUI::tr("%playcount% times");
    ThemeUI::tr("Music folders and general options");
    ThemeUI::tr("Player Settings");
    ThemeUI::tr("Music playback options");
    ThemeUI::tr("Ripper Settings");
    ThemeUI::tr("CD copying options");
    ThemeUI::tr("Play Music");
    ThemeUI::tr("Select Music");
    ThemeUI::tr("Import CD");
    ThemeUI::tr("Import Files");
    ThemeUI::tr("Scan for New Music");
    ThemeUI::tr("Eject media");
    ThemeUI::tr("Music Settings");
    ThemeUI::tr("Configure playback and CD ripping");
    ThemeUI::tr("Search Term:");
    ThemeUI::tr("Author: %1");
    ThemeUI::tr("Size: %1");
    ThemeUI::tr("Description: %1");
    ThemeUI::tr("Can't find any search scripts!  This usually indicates missing search script prerequisites.  Try running a script from the command line.");
    ThemeUI::tr("Manage Site Subscriptions");
    ThemeUI::tr("Edit");
    ThemeUI::tr("New");
    ThemeUI::tr("Remove");
    ThemeUI::tr("Manage RSS Subscriptions");
    ThemeUI::tr("Feed Name:");
    ThemeUI::tr("Feed URL:");
    ThemeUI::tr("Site Description:");
    ThemeUI::tr("Feed Author:");
    ThemeUI::tr("Download this feed automatically");
    ThemeUI::tr("Choose Image");
    ThemeUI::tr("Posted: %1");
    ThemeUI::tr("You haven't added any Sites/RSS Feeds yet!  To add a site, press MENU, then choose \"Scan/Manage Subscriptions,\" then \"Manage Site Subscriptions.\"");
    ThemeUI::tr("Runtime");
    ThemeUI::tr("Author");
    ThemeUI::tr("Rating");
    ThemeUI::tr("Search Internet Video");
    ThemeUI::tr("Search popular video sites");
    ThemeUI::tr("Browse Internet Video");
    ThemeUI::tr("Browse highlights and entire sites");
    ThemeUI::tr("Categories");
    ThemeUI::tr("Languages");
    ThemeUI::tr("Popular");
    ThemeUI::tr("Top Rated");
    ThemeUI::tr("Rip/Transcode");
    ThemeUI::tr("Job 1 of 1");
    ThemeUI::tr("Select:");
    ThemeUI::tr("Audio Track:");
    ThemeUI::tr("AC3 Audio:");
    ThemeUI::tr("Subtitles:");
    ThemeUI::tr("View:");
    ThemeUI::tr("0:00:00");
    ThemeUI::tr("Title 1 of 1");
    ThemeUI::tr("Previous");
    ThemeUI::tr("Directed by:");
    ThemeUI::tr("User Rating:");
    ThemeUI::tr("Runtime:");
    ThemeUI::tr("No videos in library, or no files found.  If you have configured a video directory, press \"M\" (or the MENU key) and select \"Scan for Changes.\"");
    ThemeUI::tr("Director:");
    ThemeUI::tr("Rated:");
    ThemeUI::tr("Parental Level:");
    ThemeUI::tr("Lowest");
    ThemeUI::tr("Low");
    ThemeUI::tr("Medium");
    ThemeUI::tr("High");
    ThemeUI::tr("Browsable:");
    ThemeUI::tr("Cover File:");
    ThemeUI::tr("Video Num.:");
    ThemeUI::tr("Directed by");
    ThemeUI::tr("Year");
    ThemeUI::tr("User Rating");
    ThemeUI::tr("Parental Level");
    ThemeUI::tr("MythVideo File Associations");
    ThemeUI::tr("Extension:");
    ThemeUI::tr("Command:");
    ThemeUI::tr("Use default player:");
    ThemeUI::tr("Ignore:");
    ThemeUI::tr("Delete");
    ThemeUI::tr("Edit Video Information");
    ThemeUI::tr("Season:");
    ThemeUI::tr("Episode:");
    ThemeUI::tr("Parental Control:");
    ThemeUI::tr("File to Always Play Next:");
    ThemeUI::tr("Visible:");
    ThemeUI::tr("Watched:");
    ThemeUI::tr("Trailer:");
    ThemeUI::tr("Unique Player Command:");
    ThemeUI::tr("Coverart");
    ThemeUI::tr("Screenshots");
    ThemeUI::tr("Banners");
    ThemeUI::tr("Fanart");
    ThemeUI::tr("Filters video list");
    ThemeUI::tr("Text Filter:");
    ThemeUI::tr("Category :");
    ThemeUI::tr("Genre :");
    ThemeUI::tr("Country :");
    ThemeUI::tr("Actor/Actress :");
    ThemeUI::tr("Year :");
    ThemeUI::tr("Runtime :");
    ThemeUI::tr("User Rating :");
    ThemeUI::tr("Browse :");
    ThemeUI::tr("InetRef :");
    ThemeUI::tr("Cover File :");
    ThemeUI::tr("Sort by :");
    ThemeUI::tr("Watched :");
    ThemeUI::tr("Result");
    ThemeUI::tr("Save as default");
    ThemeUI::tr("Default Player:");
    ThemeUI::tr("DVD Player:");
    ThemeUI::tr("DVD Drive:");
    ThemeUI::tr("VCD Player:");
    ThemeUI::tr("VCD Drive:");
    ThemeUI::tr("Enable Alternate Player:");
    ThemeUI::tr("Alternate Player:");
    ThemeUI::tr("Video Metadata Settings");
    ThemeUI::tr("Perform metadata update after video scan");
    ThemeUI::tr("Enable Random Trailer Playback");
    ThemeUI::tr("Display unknown file types");
    ThemeUI::tr("Enable metadata in file browse mode");
    ThemeUI::tr("Trailers to Play:");
    ThemeUI::tr("Include while Browsing:");
    ThemeUI::tr("Item has been watched:");
    ThemeUI::tr("Coverart:");
    ThemeUI::tr("Banner:");
    ThemeUI::tr("Find Online...");
    ThemeUI::tr("File Paths and general options");
    ThemeUI::tr("Player Applications and DVD/VCD Drives");
    ThemeUI::tr("Metadata Settings");
    ThemeUI::tr("Grabber Setup and display preferences");
    ThemeUI::tr("File Types");
    ThemeUI::tr("Associate new file extensions");
    ThemeUI::tr("Rip Settings");
    ThemeUI::tr("DVD Rip and Transcode options");
    ThemeUI::tr("Browse Videos");
    ThemeUI::tr("Video List");
    ThemeUI::tr("Video Gallery");
    ThemeUI::tr("Video Manager");
    ThemeUI::tr("Play DVD");
    ThemeUI::tr("Play VCD");
    ThemeUI::tr("Rip DVD");
    ThemeUI::tr("Videos Settings");
    ThemeUI::tr("Configure playback and DVD ripping");
    ThemeUI::tr("Humidity");
    ThemeUI::tr("Pressure");
    ThemeUI::tr("Wind(Gust)");
    ThemeUI::tr("Wind Direction");
    ThemeUI::tr("Visibility");
    ThemeUI::tr("Feels Like");
    ThemeUI::tr("Weather Alerts");
    ThemeUI::tr("Temp");
    ThemeUI::tr("Precip");
    ThemeUI::tr("Global Settings");
    ThemeUI::tr("Seconds to display each page:");
    ThemeUI::tr("Retrieve data in the background:");
    ThemeUI::tr("Screen Setup");
    ThemeUI::tr("Source Setup");
    ThemeUI::tr("Data Retrieval Interval (minutes):");
    ThemeUI::tr("Source Update Timeout (seconds):");
    ThemeUI::tr("Location Search");
    ThemeUI::tr("Enter your current location, nearest large town or city. In some countries postal codes are also supported.");
    ThemeUI::tr("Enter Location:");
    ThemeUI::tr("General weather plugin options");
    ThemeUI::tr("Screen Settings");
    ThemeUI::tr("Choose which weather forecasts to display");
    ThemeUI::tr("Source Settings");
    ThemeUI::tr("Configure the behavior of weather scripts");
    ThemeUI::tr("Edit Monitor Function");
    ThemeUI::tr("Enabled");
    ThemeUI::tr("Zone Minder Console");
    ThemeUI::tr("Status");
    ThemeUI::tr("Load: 0.12");
    ThemeUI::tr("Disk: 100%");
    ThemeUI::tr("Camera");
    ThemeUI::tr("Function");
    ThemeUI::tr("Source");
    ThemeUI::tr("Events");
    ThemeUI::tr("[R] = Running [S] = Stopped");
    ThemeUI::tr("Zone Minder Events");
    ThemeUI::tr("Select Camera");
    ThemeUI::tr("Select Date");
    ThemeUI::tr("0/0");
    ThemeUI::tr("Event Name");
    ThemeUI::tr("Date/Time");
    ThemeUI::tr("Date");
    ThemeUI::tr("Duration");
    ThemeUI::tr("Zone Minder Event Player");
    ThemeUI::tr("Event:");
    ThemeUI::tr("Event Name (1/123)");
    ThemeUI::tr("Camera:");
    ThemeUI::tr("Camera Name");
    ThemeUI::tr("Frame:");
    ThemeUI::tr("1/123");
    ThemeUI::tr("Date:");
    ThemeUI::tr("Mon 01 Nov 2006 12:34");
    ThemeUI::tr("There are no events to show");
    ThemeUI::tr("Zone Minder Live Player");
    ThemeUI::tr("Monitor 1");
    ThemeUI::tr("Monitor 2");
    ThemeUI::tr("Monitor 3");
    ThemeUI::tr("Monitor 4");
    ThemeUI::tr("Show Console");
    ThemeUI::tr("Show Live View");
    ThemeUI::tr("Show Events");
    ThemeUI::tr("Shift");
    ThemeUI::tr("Appearance Wizard");
    ThemeUI::tr("Move the selected arrow to the corner of the TV screen.  Press SELECT to edit the other arrow.  Press MENU to change the granularity of the adjustment or to quit without saving.  When you have finished, press BACK.");
    ThemeUI::tr("1920 x 1080");
    ThemeUI::tr("1 pixel");
    ThemeUI::tr("%DATE%, %TIME%");
    ThemeUI::tr("Go up a level");
    ThemeUI::tr("Web Bookmarks");
    ThemeUI::tr("Browse your favorite web sites.");
    ThemeUI::tr("Browser:");
    ThemeUI::tr("Configure Web Browser");
    ThemeUI::tr("You can edit the name, URL, and category for the selected Web Site on this screen.\n\nWhen you have finished editing, select \"OK\" or \"Cancel\" to continue.");
    ThemeUI::tr("Channel:");
    ThemeUI::tr("Click to choose from existing categories...");
    ThemeUI::tr("Twitter Timeline");
    ThemeUI::tr("Skip");
    ThemeUI::tr("Edit Channels");
    ThemeUI::tr("Modify, Add, and Delete television channels.");
    ThemeUI::tr("Sort By:");
    ThemeUI::tr("Video Source:");
    ThemeUI::tr("Delete Source");
    ThemeUI::tr("Channel Scan");
    ThemeUI::tr("Import Icons");
    ThemeUI::tr("Edit Transports");
    ThemeUI::tr("Hide Channels without channel number.");
    ThemeUI::tr("Edit On Screen Display");
    ThemeUI::tr("Select the menu items you want to see by playback mode.");
    ThemeUI::tr("OSD Context");
    ThemeUI::tr("OSD Menu Items");
    ThemeUI::tr("Edit Key Bindings");
    ThemeUI::tr("Assign custom keys to MythTV shortcuts.");
    ThemeUI::tr("Select a Title to Rip");
    ThemeUI::tr("Select the parts of the DVD you wish to copy.");
    ThemeUI::tr("Film Name:");
    ThemeUI::tr("Track Length:");
    ThemeUI::tr("Rip Quality:");
    ThemeUI::tr("Rip AC-3 Audio");
    ThemeUI::tr("Preview this title");
    ThemeUI::tr("Rip This Track");
    ThemeUI::tr("Previous Title");
    ThemeUI::tr("Next Title");
    ThemeUI::tr("Begin Ripping");
    ThemeUI::tr("No images are present in the pictures folder.");
    ThemeUI::tr("Released %1");
    ThemeUI::tr("Edit Metadata");
    ThemeUI::tr("Modify your game's metadata.");
    ThemeUI::tr("Cover Art:");
    ThemeUI::tr("Game is a Favorite");
    ThemeUI::tr("Click here to search existing coverart...");
    ThemeUI::tr("Click here to search existing screenshots...");
    ThemeUI::tr("Click here to search existing fanart...");
    ThemeUI::tr("Movie Times");
    ThemeUI::tr("Rated %1");
    ThemeUI::tr("Import Coverart");
    ThemeUI::tr("Browse cover images on your system.");
    ThemeUI::tr("Import local music files.");
    ThemeUI::tr("Track is part of a compilation");
    ThemeUI::tr("Click to browse directories...");
    ThemeUI::tr("Choose Coverart");
    ThemeUI::tr("Rip A CD");
    ThemeUI::tr("Input metadata for the CD you have inserted.");
    ThemeUI::tr("Album Name:");
    ThemeUI::tr("Album Year:");
    ThemeUI::tr("Album is a compilation");
    ThemeUI::tr("Click here to search existing artists...");
    ThemeUI::tr("Click here to search existing albums...");
    ThemeUI::tr("Click here to search existing genres...");
    ThemeUI::tr("Choose where you would like your files archived.");
    ThemeUI::tr("Output Type:");
    ThemeUI::tr("Click here to find an output location...");
    ThemeUI::tr("Erase DVD-RW before burning");
    ThemeUI::tr("Filter:");
    ThemeUI::tr("Select the file you wish to use.");
    ThemeUI::tr("See logs from your archive runs.");
    ThemeUI::tr("12.34GB");
    ThemeUI::tr("Choose the appearance of your DVD.");
    ThemeUI::tr("Theme:");
    ThemeUI::tr("Select the recordings and videos you wish to save.");
    ThemeUI::tr("Up Level");
    ThemeUI::tr("No search scripts found!  This usually indicates missing prerequisites.");
    ThemeUI::tr("Page %1");
    ThemeUI::tr("Search:");
    ThemeUI::tr("Edit/Add a New RSS Feed");
    ThemeUI::tr("Type the URL to an RSS 2.0 media feed below.  If editing an existing feed, modify any of the values you like.  Press \"Save\" to save/subscribe.\n\nFor new subscriptions, you can simply enter the URL and click \"Save.\"");
    ThemeUI::tr("Author:");
    ThemeUI::tr("Download video from this feed automatically");
    ThemeUI::tr("Select to change image...");
    ThemeUI::tr("Manage Subscriptions");
    ThemeUI::tr("Choose the sites you wish to browse/search.");
    ThemeUI::tr("New Site");
    ThemeUI::tr("Edit Site");
    ThemeUI::tr("Unsubscribe");
    ThemeUI::tr("Edit RSS News Feeds");
    ThemeUI::tr("You can edit the name, URL, and icon path for the selected RSS Feed on this screen.  You can also designate the item as a podcast.\n\nWhen you have finished editing, select \"OK\" or \"Cancel\" to continue.");
    ThemeUI::tr("Icon:");
    ThemeUI::tr("Podcast:");
    ThemeUI::tr("News Subscriptions");
    ThemeUI::tr("Choose the news sites you would like to read.");
    ThemeUI::tr("(%CHANNUM%) %TITLE%");
    ThemeUI::tr("%STARTTIME%-%ENDTIME%, %RECSTARTDATE%");
    ThemeUI::tr("%DESCRIPTION% %VALUE%%UNITS%");
    ThemeUI::tr("Channel Editor");
    ThemeUI::tr("Edit the details about this channel.");
    ThemeUI::tr("Channel #:");
    ThemeUI::tr("Chan Name:");
    ThemeUI::tr("XMLTV #:");
    ThemeUI::tr("Probe");
    ThemeUI::tr("Frame %1");
    ThemeUI::tr("Recording...");
    ThemeUI::tr("Transcoding...");
    ThemeUI::tr("Original Airdate: %1");
    ThemeUI::tr("Custom Export");
    ThemeUI::tr("Directory Format");
    ThemeUI::tr("File Format");
    ThemeUI::tr("Export");
    ThemeUI::tr("Change Group View");
    ThemeUI::tr("Enable and disable the checkboxes below to filter the way recordings are displayed.");
    ThemeUI::tr("Show Program Titles");
    ThemeUI::tr("Show Program Categories");
    ThemeUI::tr("Show Recording Groups");
    ThemeUI::tr("Show Watch List");
    ThemeUI::tr("Show Searches");
    ThemeUI::tr("Show Live TV");
    ThemeUI::tr("Show Watched Programs");
    ThemeUI::tr("Change Group Password");
    ThemeUI::tr("Old:");
    ThemeUI::tr("New:");
    ThemeUI::tr("Change Filter");
    ThemeUI::tr("Status Icon Help");
    ThemeUI::tr("These icons represent information about your recordings.");
    ThemeUI::tr("Edit Recording Metadata");
    ThemeUI::tr("Using the text areas below, you can change the recording title, subtitle, and description.\n\nOnce you have completed your modifications, click the \"OK\" button.");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%) %LONGREPEAT% %YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("Manually Schedule A Recording");
    ThemeUI::tr("To manually schedule a recording, enter a title (optional).  Then set the channel, date, start time, and duration of your recording.  Note that this recording will not have any listings data or other information provided by an EPG.");
    ThemeUI::tr("Hour:");
    ThemeUI::tr("Minute:");
    ThemeUI::tr("Duration:");
    ThemeUI::tr("No Recordings Scheduled...");
    ThemeUI::tr("Filter: %1");
    ThemeUI::tr("Priority:");
    ThemeUI::tr("To give greater or lesser priority to a channel in your lineup, select it from the list.  To increase the channel's priority, press the right arrow.  To decrease its priority, press the left arrow.");
    ThemeUI::tr("Program Title");
    ThemeUI::tr("Program/Final Priority");
    ThemeUI::tr("Type Priority:");
    ThemeUI::tr("Final Priority:");
    ThemeUI::tr("Custom Priority Rules");
    ThemeUI::tr("To create a custom priority rule, enter a name and priority adjustment.  You can them select from existing priority templates or create one of your own using SQL syntax in the \"Clause SQL\" edit box.\n\nOnce you have completed your rule, can can Test, Delete, or Install it right away.");
    ThemeUI::tr("Existing:");
    ThemeUI::tr("Rule Name:");
    ThemeUI::tr("Clause:");
    ThemeUI::tr("Clause SQL:");
    ThemeUI::tr("Click to add clause...");
    ThemeUI::tr("Test");
    ThemeUI::tr("Install");
    ThemeUI::tr("Record");
    ThemeUI::tr("Select Time");
    ThemeUI::tr("Edit Power Search");
    ThemeUI::tr("You can specify basic criteria to create powerful search and record rules.  Below, you may enter title, subtitle, and description phrases (all optional), as well as category, genre, and channel values to refine a complex search for programs.\n\nWhen you have completed your configuration, press \"OK\" to search.");
    ThemeUI::tr("Program Details");
    ThemeUI::tr("Below you will find the program details of the selected item.  There are two available screens.  You can toggle between them by pressing INFO.");
    ThemeUI::tr("First Letter:");
    ThemeUI::tr("Schedule Options");
    ThemeUI::tr("Storage Options");
    ThemeUI::tr("Post Processing");
    ThemeUI::tr("Schedule Info");
    ThemeUI::tr("Preview Schedule");
    ThemeUI::tr("Select the options for this recording.");
    ThemeUI::tr("-%n", 0, 1);
    ThemeUI::tr("Normal");
    ThemeUI::tr("+%n", 0, 1);
    ThemeUI::tr("Input:");
    ThemeUI::tr("Start Offset:");
    ThemeUI::tr("%n minute(s) late", 0, 1);
    ThemeUI::tr("Start on time");
    ThemeUI::tr("%n minute(s) early", 0, 1);
    ThemeUI::tr("End Offset:");
    ThemeUI::tr("End on time");
    ThemeUI::tr("Dup Method:");
    ThemeUI::tr("Dup Scope:");
    ThemeUI::tr("Recording Rule is Active");
    ThemeUI::tr("Select how the recording file should be treated.");
    ThemeUI::tr("Rec. Profile:");
    ThemeUI::tr("Rec. Group:");
    ThemeUI::tr("Strg. Group:");
    ThemeUI::tr("Play Group:");
    ThemeUI::tr("Max to Keep:");
    ThemeUI::tr("Max Newest:");
    ThemeUI::tr("Allow Recordings to Auto-Expire");
    ThemeUI::tr("Post Processing Options");
    ThemeUI::tr("Select any jobs you want run on the recording.");
    ThemeUI::tr("Automatically Commercial Flag Recordings");
    ThemeUI::tr("Automatically Transcode Recordings");
    ThemeUI::tr("Run User Job #1");
    ThemeUI::tr("Run User Job #2");
    ThemeUI::tr("Run User Job #3");
    ThemeUI::tr("Run User Job #4");
    ThemeUI::tr("Last Recorded/Priority");
    ThemeUI::tr("Recording Group:");
    ThemeUI::tr("Storage Group:");
    ThemeUI::tr("Recording Profile:");
    ThemeUI::tr("Create a Custom Recording Rule");
    ThemeUI::tr("To create a custom recording rule, either select an existing rule, or create a new rule by typing in a name.  Then select a rule type and hit enter.  The SQL code will be transferred below, and you can edit it and insert your own program information.\n\nFinally, you can test, immediately activate, store, or cancel your rule.");
    ThemeUI::tr("Rule Type:");
    ThemeUI::tr("Rule SQL:");
    ThemeUI::tr("Tables:");
    ThemeUI::tr("Store");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded...");
    ThemeUI::tr("System Status");
    ThemeUI::tr("Learn what your system is up to.");
    ThemeUI::tr("Arclight is a sleek theme meant for widescreen HD screens.  It is high contrast and uses shapes and attractive layout to convey information simply, consistently, and attractively.");
    ThemeUI::tr("Type your tweet below.  Select \"Send\" to submit it.");
    ThemeUI::tr("Send");
    ThemeUI::tr("Enter Your Twitter Login Details");
    ThemeUI::tr("Login:");
    ThemeUI::tr("Password:");
    ThemeUI::tr("Send a Tweet");
    ThemeUI::tr("User Rating: %1");
    ThemeUI::tr("Cast");
    ThemeUI::tr("Plot");
    ThemeUI::tr("Season/Episode: %1");
    ThemeUI::tr("Starring: %1");
    ThemeUI::tr("Parental Level 0");
    ThemeUI::tr("Parental Level 1");
    ThemeUI::tr("Parental Level 2");
    ThemeUI::tr("Parental Level 3");
    ThemeUI::tr("Parental Level 4");
    ThemeUI::tr("Add New File Types");
    ThemeUI::tr("On this screen, you can add new extensions to be recognized by the Video Plugin.  If a scan does not add your files, create a new extension below by clicking the \"New\" button.\n\nIf you select \"Use Default Player,\" the player command set for the extension will be ignored.  \"Ignore This File Type\" prevents the items from appearing in a scan.");
    ThemeUI::tr("Use Default Player");
    ThemeUI::tr("Ignore This File Type");
    ThemeUI::tr("Tagline:");
    ThemeUI::tr("TMDB Number:");
    ThemeUI::tr("Homepage:");
    ThemeUI::tr("Custom Player:");
    ThemeUI::tr("Next File:");
    ThemeUI::tr("Click to select from online coverart...");
    ThemeUI::tr("Click to select from online screenshots...");
    ThemeUI::tr("Click here to search existing banners...");
    ThemeUI::tr("Click to select from online banners...");
    ThemeUI::tr("Click to select from online fanart...");
    ThemeUI::tr("Click here to search existing trailers...");
    ThemeUI::tr("Filter Videos");
    ThemeUI::tr("Actor/Actress:");
    ThemeUI::tr("Browse:");
    ThemeUI::tr("TMDB/TVDB #:");
    ThemeUI::tr("Directed by %1");
    ThemeUI::tr("This item was released on %1.");
    ThemeUI::tr("It was added to your collection on %1.");
    ThemeUI::tr("Video Player Settings");
    ThemeUI::tr("Default:");
    ThemeUI::tr("Enable Alternate Player");
    ThemeUI::tr("Alt. Player:");
    ThemeUI::tr("Update metadata after video scan");
    ThemeUI::tr("Trailer #:");
    ThemeUI::tr("Last Updated %1");
    ThemeUI::tr("High Temperature:  %1");
    ThemeUI::tr("Low Temperature:  %1");
    ThemeUI::tr("Temperature:  %1");
    ThemeUI::tr("Chance of Precipitation:  %1");
    ThemeUI::tr("Weather Screen Settings");
    ThemeUI::tr("This screen governs the behavior of the weather screens.  You can enable a background weather update which will run regardless of being on the weather screen, and configure how many seconds each screen will display.\n\nWhen you are done configuring the Weather Plugin, click \"Finish\" to continue.");
    ThemeUI::tr("Retrieve data in background:");
    ThemeUI::tr("Weather Setup");
    ThemeUI::tr("Available Screens");
    ThemeUI::tr("Active Screens");
    ThemeUI::tr("Weather Script Settings");
    ThemeUI::tr("This settings screen governs the behavior of individual weather scripts.  Select the script whose behavior you with to change and press the right arrow. Adjust the interval at which data is retrieved, and the timeout for accessing the site.\n\nWhen you have completed your changes, click \"Finish\" to continue.");
    ThemeUI::tr("Enter Current Location");
    ThemeUI::tr("Welcome to MythTV");
    ThemeUI::tr("MythTV is idle and will shut down shortly.");
    ThemeUI::tr("Current Recording(s):");
    ThemeUI::tr("Retrieving Recording Status...");
    ThemeUI::tr("Next Scheduled Recording(s):");
    ThemeUI::tr("Retrieving Scheduled Recordings...");
    ThemeUI::tr("WARNING: There are conflicting scheduled recordings!");
    ThemeUI::tr("Image Gallery");
    ThemeUI::tr("Move the selected arrow to the corner of the TV screen.  Press SELECT to edit the other arrow.  Press MENU for options and ESC to quit.");
    ThemeUI::tr("1280 x 720");
    ThemeUI::tr("0 x 0");
    ThemeUI::tr("Phrase");
    ThemeUI::tr("Up");
    ThemeUI::tr("Please wait...");
    ThemeUI::tr("Icon Downloader");
    ThemeUI::tr("Search terms:");
    ThemeUI::tr("Sort Mode:");
    ThemeUI::tr("Icon Download");
    ThemeUI::tr("OSD Menu Editor");
    ThemeUI::tr("State");
    ThemeUI::tr("Menu Item");
    ThemeUI::tr("Edit Keys");
    ThemeUI::tr("Contexts");
    ThemeUI::tr("Actions");
    ThemeUI::tr("Overall Progress");
    ThemeUI::tr("Job Progress");
    ThemeUI::tr("Preview Track");
    ThemeUI::tr("Play Games");
    ThemeUI::tr("Television");
    ThemeUI::tr("Music");
    ThemeUI::tr("Gallery");
    ThemeUI::tr("Videos");
    ThemeUI::tr("Weather");
    ThemeUI::tr("Schedule");
    ThemeUI::tr("Program Search");
    ThemeUI::tr("Setup");
    ThemeUI::tr("Optical");
    ThemeUI::tr("Media Library");
    ThemeUI::tr("Info Center");
    ThemeUI::tr("Running Time:");
    ThemeUI::tr("Show Times:");
    ThemeUI::tr("Scan");
    ThemeUI::tr("All ready in database");
    ThemeUI::tr("Album");
    ThemeUI::tr("Genre");
    ThemeUI::tr("Video Category:");
    ThemeUI::tr("Search Net Videos");
    ThemeUI::tr("Browse Net Videos");
    ThemeUI::tr("News Feeds");
    ThemeUI::tr("News Settings");
    ThemeUI::tr("Web Site");
    ThemeUI::tr("Watch Recordings");
    ThemeUI::tr("Status Icons");
    ThemeUI::tr("Show Titles");
    ThemeUI::tr("Show Categories");
    ThemeUI::tr("Show LiveTV");
    ThemeUI::tr("Change Recording Group Password");
    ThemeUI::tr("Old Password:");
    ThemeUI::tr("New Password:");
    ThemeUI::tr("Program Guide");
    ThemeUI::tr("%YEARSTARS% %DESCRIPTION% %LONGREPEAT%");
    ThemeUI::tr("Manual Recording Schedule");
    ThemeUI::tr("Title (Optional):");
    ThemeUI::tr("Date, or day of week:");
    ThemeUI::tr("Hour");
    ThemeUI::tr("Minute");
    ThemeUI::tr("Scheduled Recordings");
    ThemeUI::tr("Showing:");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("Channel Priorities");
    ThemeUI::tr("Source:");
    ThemeUI::tr("(1) Channel (2) Priority");
    ThemeUI::tr("Channel Recording Priorities");
    ThemeUI::tr("Schedule Priorities");
    ThemeUI::tr("Priority");
    ThemeUI::tr("Final");
    ThemeUI::tr("Hello");
    ThemeUI::tr("(1) Title (2) Priority (4) Type");
    ThemeUI::tr("Existing Rules:");
    ThemeUI::tr("Priority Change:");
    ThemeUI::tr("Select a clause from the list.");
    ThemeUI::tr("Add Clause");
    ThemeUI::tr("Select Search");
    ThemeUI::tr("Edit Power Search Fields");
    ThemeUI::tr("Optional title phrase:");
    ThemeUI::tr("Optional subtitle phrase:");
    ThemeUI::tr("Optional description phrase:");
    ThemeUI::tr("Program List");
    ThemeUI::tr("Program Finder");
    ThemeUI::tr("%|\"SUBTITLE|\"% %LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("Select the recording rule");
    ThemeUI::tr("Preview");
    ThemeUI::tr("Reduce priority by %n", 0, 1);
    ThemeUI::tr("Normal recording priority");
    ThemeUI::tr("Raise priority by %n", 0, 1);
    ThemeUI::tr("Start recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Start recording on time");
    ThemeUI::tr("Start recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording on time");
    ThemeUI::tr("End recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Recording Rule Active");
    ThemeUI::tr("No episode limit");
    ThemeUI::tr("Keep at most %n episode(s)", 0, 1);
    ThemeUI::tr("Allow recordings to expire?");
    ThemeUI::tr("Commercial Flag new recordings");
    ThemeUI::tr("Transcode new recordings");
    ThemeUI::tr("Custom Record Rules");
    ThemeUI::tr("Additional Tables:");
    ThemeUI::tr("Preview Schedule Changes");
    ThemeUI::tr("Recording Rules");
    ThemeUI::tr("My first attempt at a theme, aimed at creating a theme suitable for children.");
    ThemeUI::tr("Video File Associations");
    ThemeUI::tr("Edit Video Metadata");
    ThemeUI::tr("File to Play Next:");
    ThemeUI::tr("Item has been Watched:");
    ThemeUI::tr("Search Results");
    ThemeUI::tr("Cast Members");
    ThemeUI::tr("Full Plot");
    ThemeUI::tr("Video List Filters");
    ThemeUI::tr("Country");
    ThemeUI::tr("Actor/Actress");
    ThemeUI::tr("Browse");
    ThemeUI::tr("InetRef");
    ThemeUI::tr("Cover File");
    ThemeUI::tr("Sort by");
    ThemeUI::tr("Watched");
    ThemeUI::tr("Make default");
    ThemeUI::tr("Videos - Manager");
    ThemeUI::tr("Cast:");
    ThemeUI::tr("Videos - Browser");
    ThemeUI::tr("Videos - Gallery");
    ThemeUI::tr("Videos - Tree");
    ThemeUI::tr("Movie Grabber:");
    ThemeUI::tr("TV Grabber:");
    ThemeUI::tr("Weather Screen Setup");
    ThemeUI::tr("Weather Source Setup");
    ThemeUI::tr("Filename");
    ThemeUI::tr("Select an Icon");
    ThemeUI::tr("Icon Download Status...");
    ThemeUI::tr("This screen displays the status of various system components");
    ThemeUI::tr("No Current Jobs");
    ThemeUI::tr("Select a Track to Rip");
    ThemeUI::tr("Name of Film:");
    ThemeUI::tr("Selected track length:");
    ThemeUI::tr("Check this box to select this track:");
    ThemeUI::tr("Check to rip AC-3 audio:");
    ThemeUI::tr("Press to view excerpt:");
    ThemeUI::tr("ROM Name:");
    ThemeUI::tr("ROM Path:");
    ThemeUI::tr("Edit RSS News Feed");
    ThemeUI::tr("%|\"SUBTITLE|\"%");
    ThemeUI::tr("No Recordings Present...");
    ThemeUI::tr("Change View");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%) %LONGREPEAT%%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and Select 'Program Guide' or 'Program Finder' ");
    ThemeUI::tr("Search Term");
    ThemeUI::tr("Program Details:");
    ThemeUI::tr("Show Name:");
    ThemeUI::tr("Air Date:");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("Dupe Method:");
    ThemeUI::tr("Dupe Scope:");
    ThemeUI::tr("Rec Profile:");
    ThemeUI::tr("Rec Group:");
    ThemeUI::tr("# to Keep:");
    ThemeUI::tr("Limit Handling:");
    ThemeUI::tr("Graphite is a theme emphasizing MythUI interface improvements such as alpha, animation, unique layouts, and user-supplied backdrop content.  It is extremely memory-hungry.");
    ThemeUI::tr("TMDB:");
    ThemeUI::tr("Parental Lvl:");
    ThemeUI::tr("Browseable");
    ThemeUI::tr("Player Command:");
    ThemeUI::tr("Text Filter :");
    ThemeUI::tr("Seas/Ep:");
    ThemeUI::tr("Weather Location Search");
    ThemeUI::tr("SELECT: View");
    ThemeUI::tr("MENU: Activate Menu");
    ThemeUI::tr("Theater name");
    ThemeUI::tr("%|\"SUBTITLE|\"% %STARS% %DESCRIPTION%");
    ThemeUI::tr("No Recordings available, or screen loading...");
    ThemeUI::tr("%LONGREPEAT%%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("(1) All  (2) Important");
    ThemeUI::tr("Program Listings");
    ThemeUI::tr("No listings found for this program.");
    ThemeUI::tr("Enter Search Text");
    ThemeUI::tr("Close");
    ThemeUI::tr("Search For:");
    ThemeUI::tr("Manage Recording Rules");
    ThemeUI::tr("Channel");
    ThemeUI::tr("Last Recorded");
    ThemeUI::tr("Schedule Editor");
    ThemeUI::tr("Schedule Options Editor");
    ThemeUI::tr("Storage Options Editor");
    ThemeUI::tr("Post Processing Editor");
    ThemeUI::tr("Run User job #2");
    ThemeUI::tr("Mythbuntu is based on ProjectGrayhem - a dark, shiny theme originally inspired by XBMC's ProjectMayhem skin");
    ThemeUI::tr("Background:");
    ThemeUI::tr("Humidity:");
    ThemeUI::tr("Pressure:");
    ThemeUI::tr("Wind(Gust):");
    ThemeUI::tr("Wind Direction:");
    ThemeUI::tr("Visibility:");
    ThemeUI::tr("Feels Like:");
    ThemeUI::tr("MythTV is idle and will shutdown shortly.");
    ThemeUI::tr("Current Recording(s)");
    ThemeUI::tr("Next Scheduled Recording(s)");
    ThemeUI::tr("Key Configuration");
    ThemeUI::tr("Utilities");
    ThemeUI::tr("Manage Recordings");
    ThemeUI::tr("Information");
    ThemeUI::tr("Optical Media");
    ThemeUI::tr("Schedule Recordings");
    ThemeUI::tr("Photographs");
    ThemeUI::tr("Media Setup");
    ThemeUI::tr("Info Setup");
    ThemeUI::tr("TV Setup");
    ThemeUI::tr("DVD");
    ThemeUI::tr("Music Setup");
    ThemeUI::tr("Video Setup");
    ThemeUI::tr("Game Setup");
    ThemeUI::tr("NetFlix");
    ThemeUI::tr("Archive");
    ThemeUI::tr("Search Words");
    ThemeUI::tr("Search Lists");
    ThemeUI::tr("Edit Playlist");
    ThemeUI::tr("Edit AlbumArt");
    ThemeUI::tr("Ripping CD");
    ThemeUI::tr("Directory Finder");
    ThemeUI::tr("/some/file/goes/here/test.mp3");
    ThemeUI::tr("123 of 345");
    ThemeUI::tr("NetFlix Browser");
    ThemeUI::tr("NetFlix Queue");
    ThemeUI::tr("MythFlix Configuration");
    ThemeUI::tr("RSS Feeds");
    ThemeUI::tr("MythNews Configuration");
    ThemeUI::tr("Minutes");
    ThemeUI::tr("%SUBTITLE|\"|\" %%DESCRIPTION%");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%)  %LENMINS%");
    ThemeUI::tr("%CHANNUM%");
    ThemeUI::tr("%CALLSIGN%");
    ThemeUI::tr("Callsign");
    ThemeUI::tr("Channel #");
    ThemeUI::tr("Channel Name");
    ThemeUI::tr("XMLTV ID");
    ThemeUI::tr("No recordings exist");
    ThemeUI::tr("Delete Recordings");
    ThemeUI::tr("Old Password");
    ThemeUI::tr("New Password");
    ThemeUI::tr("Subtitle");
    ThemeUI::tr("Manual Recording");
    ThemeUI::tr("Upcoming Recordings");
    ThemeUI::tr("%YEARSTARS| %%DESCRIPTION%%| LONGREPEAT%");
    ThemeUI::tr("Programme Finder");
    ThemeUI::tr("Programme Guide");
    ThemeUI::tr("Previously Recorded");
    ThemeUI::tr("(1) Time (2) Title");
    ThemeUI::tr("No programs matched this search.");
    ThemeUI::tr("A brushed metal and glass effect theme with a choice of colour schemes.");
    ThemeUI::tr("SELECT: Edit");
    ThemeUI::tr("INFO - Action Menu");
    ThemeUI::tr("Global Setup");
    ThemeUI::tr("Start Frontend");
    ThemeUI::tr("1. General");
    ThemeUI::tr("2. Capture cards");
    ThemeUI::tr("3. Video sources");
    ThemeUI::tr("4. Input connections");
    ThemeUI::tr("5. Channel Editor");
    ThemeUI::tr("6. Storage Directories");
    ThemeUI::tr("7. System Events");
    ThemeUI::tr("%alert_text%");
    ThemeUI::tr("LINE #%caller_line%");
    ThemeUI::tr("NAME: %caller_name%");
    ThemeUI::tr("NUM : %caller_number%");
    ThemeUI::tr("DATE: %caller_date% TIME : %caller_time%");
    ThemeUI::tr("General");
    ThemeUI::tr("Core MythTV behavior and system settings");
    ThemeUI::tr("Appearance");
    ThemeUI::tr("pick the theme, font, size, and locale");
    ThemeUI::tr("Screen Setup Wizards");
    ThemeUI::tr("Compensate for TVs with overscan");
    ThemeUI::tr("TV Settings");
    ThemeUI::tr("Settings for TV recording and playback");
    ThemeUI::tr("Images Settings");
    ThemeUI::tr("Configure display of image gallery");
    ThemeUI::tr("Game Settings");
    ThemeUI::tr("Configure playback of games");
    ThemeUI::tr("Weather Settings");
    ThemeUI::tr("Weather locale and sources");
    ThemeUI::tr("Choose which news sources interest you");
    ThemeUI::tr("Web Settings");
    ThemeUI::tr("Manage web bookmarks");
    ThemeUI::tr("Recipe Settings");
    ThemeUI::tr("Archive Files Settings");
    ThemeUI::tr("Configure how to archive video to DVD");
    ThemeUI::tr("ZoneMinder Settings");
    ThemeUI::tr("Set up surveillance software");
    ThemeUI::tr("Play Recordings");
    ThemeUI::tr("See what will be recorded next");
    ThemeUI::tr("Pick shows to record");
    ThemeUI::tr("Recording Priorities");
    ThemeUI::tr("Prioritize some shows over others");
    ThemeUI::tr("What your system is doing right now");
    ThemeUI::tr("Utilities / Setup");
    ThemeUI::tr("Settings for TV, Images, Music, Video, Weather, etc.");
    ThemeUI::tr("Set Recording Priorities");
    ThemeUI::tr("Settings to prioritize some shows over others");
    ThemeUI::tr("Set Channel Recording Priorities");
    ThemeUI::tr("Settings to prioritize some channels over others");
    ThemeUI::tr("Custom Priority");
    ThemeUI::tr("Most used DVR options are found on the main menu. Plugin options are in the utilities menu.");
    ThemeUI::tr("New Titles");
    ThemeUI::tr("Pick a program to record for a list of new titles");
    ThemeUI::tr("Movies");
    ThemeUI::tr("Pick a movie to record");
    ThemeUI::tr("Pick a program based on category");
    ThemeUI::tr("Channels");
    ThemeUI::tr("Pick a program on a given channel");
    ThemeUI::tr("Time");
    ThemeUI::tr("Pick a program based on time");
    ThemeUI::tr("Choose programs from a grid-style list");
    ThemeUI::tr("Choose programs from an alphabetical index");
    ThemeUI::tr("Find programs matching search words");
    ThemeUI::tr("Pick a program to record from a set of lists");
    ThemeUI::tr("Custom Record");
    ThemeUI::tr("Advanced program finder");
    ThemeUI::tr("Manual Schedule");
    ThemeUI::tr("VCR-like recording scheduler");
    ThemeUI::tr("Titles");
    ThemeUI::tr("Find a program based on title");
    ThemeUI::tr("Keywords");
    ThemeUI::tr("Find a program matching a keyword");
    ThemeUI::tr("People");
    ThemeUI::tr("Find a program including a given person");
    ThemeUI::tr("Advanced");
    ThemeUI::tr("Combine more than one word search");
    ThemeUI::tr("Stored Searches");
    ThemeUI::tr("Results of searches you have saved");
    ThemeUI::tr("TV navigation and recording preferences");
    ThemeUI::tr("Guide appearance and behavior");
    ThemeUI::tr("Playback");
    ThemeUI::tr("Settings for viewing and playing TV");
    ThemeUI::tr("Playback OSD");
    ThemeUI::tr("Theme and settings for OSD");
    ThemeUI::tr("Playback Groups");
    ThemeUI::tr("Adjust settings for different playback styles");
    ThemeUI::tr("Channel Groups");
    ThemeUI::tr("Recording Profiles");
    ThemeUI::tr("Global recording priority and scheduling");
    ThemeUI::tr("Watch TV");
    ThemeUI::tr("Watch live television");
    ThemeUI::tr("Remove television recordings");
    ThemeUI::tr("See what you have recorded before");
    ThemeUI::tr("TV Utilities");
    ThemeUI::tr("Images");
    ThemeUI::tr("Web");
    ThemeUI::tr("Recipes");
    ThemeUI::tr("Archive Files");
    ThemeUI::tr("Zone Minder");
    ThemeUI::tr("%TIME%");
    ThemeUI::tr("Search For");
    ThemeUI::tr("A blue theme.");
    ThemeUI::tr("Sample Clauses:");
    ThemeUI::tr(" This was adapted from the Jeroen Brosens' MythCenter theme. The fonts have been changed to freely redistributable ones and layout changes have been made to make this theme look good on 1280x720 and 1920x1080 screens with a 1:1 pixel aspect ratio. ");
    ThemeUI::tr("dddd\ndd MMMM yyyy");
    ThemeUI::tr("Heading");
    ThemeUI::tr("%DATE%");
    ThemeUI::tr("hh:mm");
    ThemeUI::tr("Playback starting...");
    ThemeUI::tr("Web Page");
    ThemeUI::tr("Icon Importer");
    ThemeUI::tr("List Options");
    ThemeUI::tr("Delete All");
    ThemeUI::tr("Global Options");
    ThemeUI::tr("No images found in configured directory.  Are you sure you have set up the plugin properly?");
    ThemeUI::tr("Emulator:");
    ThemeUI::tr("Programme Searches");
    ThemeUI::tr("CD/DVD Options");
    ThemeUI::tr("Info Centre");
    ThemeUI::tr("Playing:");
    ThemeUI::tr("None");
    ThemeUI::tr("%TITLE%  by  %ARTIST%");
    ThemeUI::tr("Internet Video Browser");
    ThemeUI::tr("No sites configured!");
    ThemeUI::tr("%|\"SUBTITLE|\"% %DESCRIPTION%");
    ThemeUI::tr("Change Displayed Groups");
    ThemeUI::tr("Show Watched Recordings");
    ThemeUI::tr("Schedules Overview");
    ThemeUI::tr("First Conflict:");
    ThemeUI::tr("Recording Rule Priorities");
    ThemeUI::tr("Type");
    ThemeUI::tr("List Overview");
    ThemeUI::tr("Current View:");
    ThemeUI::tr("Position:");
    ThemeUI::tr("Rule Overview");
    ThemeUI::tr("Post-Processing Options");
    ThemeUI::tr("Parental:");
    ThemeUI::tr("IMDB ID:");
    ThemeUI::tr("Video Browser");
    ThemeUI::tr("Change MythTV key bindings.");
    ThemeUI::tr("MythStream Settings");
    ThemeUI::tr("Weather Station Settings");
    ThemeUI::tr("TV");
    ThemeUI::tr("Internet Video");
    ThemeUI::tr("Play Online Streams");
    ThemeUI::tr("Weather Station");
    ThemeUI::tr("A long menu which breaks down the options by their category. TV, Music, Video etc");
    ThemeUI::tr("Search Listings");
    ThemeUI::tr("Edit or delete any recording rule");
    ThemeUI::tr("Play TV Recordings");
    ThemeUI::tr("Select the country in which you currently reside");
    ThemeUI::tr("Language");
    ThemeUI::tr("Select your preferred language");
    ThemeUI::tr("%STARTTIME%-%ENDTIME% : %LENMINS%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded");
    ThemeUI::tr("dddd\ndd MMM yyyy");
    ThemeUI::tr("(1)Time (2)Title");
    ThemeUI::tr("Keep up with the news");
    ThemeUI::tr("Twitter");
    ThemeUI::tr("Send and receive tweets");
    ThemeUI::tr("Local weather forecast");
    ThemeUI::tr("Browse the web");
    ThemeUI::tr("Start cooking!");
    ThemeUI::tr("See what your system is doing");
    ThemeUI::tr("Home surveillance");
    ThemeUI::tr("Hardware profile");
    ThemeUI::tr("Tell us what hardware you have so we can support it");
    ThemeUI::tr("Browse your recordings");
    ThemeUI::tr("Watch Videos");
    ThemeUI::tr("Browse your video library");
    ThemeUI::tr("Listen to Music");
    ThemeUI::tr("Browse your music library");
    ThemeUI::tr("Look at Pictures");
    ThemeUI::tr("Play video games");
    ThemeUI::tr("Pick the theme, font, size, and locale");
    ThemeUI::tr("Media Settings");
    ThemeUI::tr("Settings for all non-TV media");
    ThemeUI::tr("Info Center Settings");
    ThemeUI::tr("Configure weather, news, movie info, web, and recipes");
    ThemeUI::tr("System Event Handlers");
    ThemeUI::tr("Configure System Event handler commands");
    ThemeUI::tr("Play any of your media");
    ThemeUI::tr("Pick and prioritize recordings");
    ThemeUI::tr("Information Center");
    ThemeUI::tr("Information and Communications");
    ThemeUI::tr("Optical Disks");
    ThemeUI::tr("Play or import CDs and DVDs");
    ThemeUI::tr("Configure MythTV and plugins");
    ThemeUI::tr("See what you have recorded");
    ThemeUI::tr("Set Priorities");
    ThemeUI::tr("Play a film on DVD");
    ThemeUI::tr("Play the video on a VCD");
    ThemeUI::tr("Import DVD");
    ThemeUI::tr("Import video from a movie DVD");
    ThemeUI::tr("Write video to a data DVD");
    ThemeUI::tr("Import music from an audio CD");
    ThemeUI::tr("Eject CD or DVD from drive");
    ThemeUI::tr("Prioritize some channels over others");
    ThemeUI::tr("Prioritize some recordings over others");
    ThemeUI::tr("Group your favorite channels together");
    ThemeUI::tr("Change the quality of your recordings");
    ThemeUI::tr("Music Tools");
    ThemeUI::tr("Select, import, or play music");
    ThemeUI::tr("Pick and prioritize shows to record");
    ThemeUI::tr("Play or import audio or video CDs or DVDs");
    ThemeUI::tr("Play recordings");
    ThemeUI::tr("Play videos");
    ThemeUI::tr("Watch A DVD");
    ThemeUI::tr("Play the video on a movie DVD");
    ThemeUI::tr("Watch Live TV");
    ThemeUI::tr("Watch Online Streams");
    ThemeUI::tr("Plugins");
    ThemeUI::tr("Other Plugins");
    ThemeUI::tr("Advanced Options");
    ThemeUI::tr("A \"Media Center\" menu theme. This menu theme is basically meant to bring the common \"media player/DVR\" functionality to the forefront, organize the plugins, and to make some of myth's more daunting options a little more subtle. Places the common media items on the top level (Recordings, Videos, TV, DVD, Music), places all informational plugins in \"Plugins.\" Puts all setup and scheduling in \"Advanced.\" The top two menu levels will seem new, the ones beneath Advanced->Setup are as in the default menu.");
}
