void strings_null() {
    ThemeUI::tr("Shift");
    ThemeUI::tr("Done");
    ThemeUI::tr("Appearance Wizard");
    ThemeUI::tr("Move the selected arrow to the corner of the TV screen.  Press SELECT to edit the other arrow.  Press MENU to change the granularity of the adjustment or to quit without saving.  When you have finished, press BACK.");
    ThemeUI::tr("1920 x 1080");
    ThemeUI::tr("1 pixel");
    ThemeUI::tr("New");
    ThemeUI::tr("0%");
    ThemeUI::tr("OK");
    ThemeUI::tr("Cancel");
    ThemeUI::tr("Go up a level");
    ThemeUI::tr("Home");
    ThemeUI::tr("Ok");
    ThemeUI::tr("Please Wait...");
    ThemeUI::tr("Twitter Timeline");
    ThemeUI::tr("Search");
    ThemeUI::tr("Skip");
    ThemeUI::tr("Edit Channels");
    ThemeUI::tr("Modify, Add, and Delete television channels.");
    ThemeUI::tr("Sort By:");
    ThemeUI::tr("Video Source:");
    ThemeUI::tr("Delete Source");
    ThemeUI::tr("Channel Scan");
    ThemeUI::tr("Import Icons");
    ThemeUI::tr("Edit Transports");
    ThemeUI::tr("Hide Channels without channel number.");
    ThemeUI::tr("Edit On Screen Display");
    ThemeUI::tr("Select the menu items you want to see by playback mode.");
    ThemeUI::tr("OSD Context");
    ThemeUI::tr("OSD Menu Items");
    ThemeUI::tr("Edit Key Bindings");
    ThemeUI::tr("Assign custom keys to MythTV shortcuts.");
    ThemeUI::tr("Select Archive Items");
    ThemeUI::tr("Select the recordings and videos you wish to save.");
    ThemeUI::tr("No files are selected for archive");
    ThemeUI::tr("Add Recording");
    ThemeUI::tr("Add Video");
    ThemeUI::tr("Previous");
    ThemeUI::tr("Next");
    ThemeUI::tr("File Finder");
    ThemeUI::tr("Select the file you wish to use.");
    ThemeUI::tr("Up Level");
    ThemeUI::tr("Select Associated Channel");
    ThemeUI::tr("Archived Channel");
    ThemeUI::tr("Chan. ID:");
    ThemeUI::tr("Chan. No:");
    ThemeUI::tr("Callsign:");
    ThemeUI::tr("Name:");
    ThemeUI::tr("Local Channel");
    ThemeUI::tr("Search Channel");
    ThemeUI::tr("Search Callsign");
    ThemeUI::tr("Search Name");
    ThemeUI::tr("Prev");
    ThemeUI::tr("Finish");
    ThemeUI::tr("Recording...");
    ThemeUI::tr("Transcoding...");
    ThemeUI::tr("Original Airdate: %1");
    ThemeUI::tr("Custom Export");
    ThemeUI::tr("Directory Format");
    ThemeUI::tr("Season:");
    ThemeUI::tr("Episode:");
    ThemeUI::tr("File Format");
    ThemeUI::tr("Export");
    ThemeUI::tr("Change Group View");
    ThemeUI::tr("Enable and disable the checkboxes below to filter the way recordings are displayed.");
    ThemeUI::tr("Show Program Titles");
    ThemeUI::tr("Show Program Categories");
    ThemeUI::tr("Show Recording Groups");
    ThemeUI::tr("Show Watch List");
    ThemeUI::tr("Show Searches");
    ThemeUI::tr("Show Live TV");
    ThemeUI::tr("Show Watched Programs");
    ThemeUI::tr("Save");
    ThemeUI::tr("Change Group Password");
    ThemeUI::tr("Old:");
    ThemeUI::tr("New:");
    ThemeUI::tr("Change Filter");
    ThemeUI::tr("Status Icon Help");
    ThemeUI::tr("These icons represent information about your recordings.");
    ThemeUI::tr("Edit Recording Metadata");
    ThemeUI::tr("Using the text areas below, you can change the recording title, subtitle, and description.\n\nOnce you have completed your modifications, click the \"OK\" button.");
    ThemeUI::tr("Title:");
    ThemeUI::tr("Subtitle:");
    ThemeUI::tr("Description:");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%) %LONGREPEAT% %YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("Manually Schedule A Recording");
    ThemeUI::tr("To manually schedule a recording, enter a title (optional).  Then set the channel, date, start time, and duration of your recording.  Note that this recording will not have any listings data or other information provided by an EPG.");
    ThemeUI::tr("Channel:");
    ThemeUI::tr("Date:");
    ThemeUI::tr("Hour:");
    ThemeUI::tr("Minute:");
    ThemeUI::tr("Duration:");
    ThemeUI::tr("No Recordings Scheduled...");
    ThemeUI::tr("Filter: %1");
    ThemeUI::tr("Priority:");
    ThemeUI::tr("To give greater or lesser priority to a channel in your lineup, select it from the list.  To increase the channel's priority, press the right arrow.  To decrease its priority, press the left arrow.");
    ThemeUI::tr("Program Title");
    ThemeUI::tr("Program/Final Priority");
    ThemeUI::tr("Category:");
    ThemeUI::tr("Sort By:\n(1) Title (2) Priority (4) Type");
    ThemeUI::tr("Type Priority:");
    ThemeUI::tr("Final Priority:");
    ThemeUI::tr("Custom Priority Rules");
    ThemeUI::tr("To create a custom priority rule, enter a name and priority adjustment.  You can them select from existing priority templates or create one of your own using SQL syntax in the \"Clause SQL\" edit box.\n\nOnce you have completed your rule, can can Test, Delete, or Install it right away.");
    ThemeUI::tr("Existing:");
    ThemeUI::tr("Rule Name:");
    ThemeUI::tr("Clause:");
    ThemeUI::tr("Clause SQL:");
    ThemeUI::tr("Click to add clause...");
    ThemeUI::tr("Test");
    ThemeUI::tr("Delete");
    ThemeUI::tr("Install");
    ThemeUI::tr("Record");
    ThemeUI::tr("Select Time");
    ThemeUI::tr("Edit Power Search");
    ThemeUI::tr("You can specify basic criteria to create powerful search and record rules.  Below, you may enter title, subtitle, and description phrases (all optional), as well as category, genre, and channel values to refine a complex search for programs.\n\nWhen you have completed your configuration, press \"OK\" to search.");
    ThemeUI::tr("Genre:");
    ThemeUI::tr("Filter:");
    ThemeUI::tr("Program Details");
    ThemeUI::tr("Below you will find the program details of the selected item.  There are two available screens.  You can toggle between them by pressing INFO.");
    ThemeUI::tr("First Letter:");
    ThemeUI::tr("Schedule Options");
    ThemeUI::tr("Storage Options");
    ThemeUI::tr("Post Processing");
    ThemeUI::tr("Schedule Info");
    ThemeUI::tr("Preview Schedule");
    ThemeUI::tr("Select the options for this recording.");
    ThemeUI::tr("-%n", 0, 1);
    ThemeUI::tr("Normal");
    ThemeUI::tr("+%n", 0, 1);
    ThemeUI::tr("Input:");
    ThemeUI::tr("Start Offset:");
    ThemeUI::tr("%n minute(s) late", 0, 1);
    ThemeUI::tr("Start on time");
    ThemeUI::tr("%n minute(s) early", 0, 1);
    ThemeUI::tr("End Offset:");
    ThemeUI::tr("End on time");
    ThemeUI::tr("Dup Method:");
    ThemeUI::tr("Dup Scope:");
    ThemeUI::tr("Recording Rule is Active");
    ThemeUI::tr("Select how the recording file should be treated.");
    ThemeUI::tr("Rec. Profile:");
    ThemeUI::tr("Rec. Group:");
    ThemeUI::tr("Strg. Group:");
    ThemeUI::tr("Play Group:");
    ThemeUI::tr("Max to Keep:");
    ThemeUI::tr("Max Newest:");
    ThemeUI::tr("Allow Recordings to Auto-Expire");
    ThemeUI::tr("Post Processing Options");
    ThemeUI::tr("Select any jobs you want run on the recording.");
    ThemeUI::tr("Automatically Commercial Flag Recordings");
    ThemeUI::tr("Automatically Transcode Recordings");
    ThemeUI::tr("Run User Job #1");
    ThemeUI::tr("Run User Job #2");
    ThemeUI::tr("Run User Job #3");
    ThemeUI::tr("Run User Job #4");
    ThemeUI::tr("Last Recorded/Priority");
    ThemeUI::tr("Recording Group:");
    ThemeUI::tr("Storage Group:");
    ThemeUI::tr("Recording Profile:");
    ThemeUI::tr("Create a Custom Recording Rule");
    ThemeUI::tr("To create a custom recording rule, either select an existing rule, or create a new rule by typing in a name.  Then select a rule type and hit enter.  The SQL code will be transferred below, and you can edit it and insert your own program information.\n\nFinally, you can test, immediately activate, store, or cancel your rule.");
    ThemeUI::tr("Rule Type:");
    ThemeUI::tr("Rule SQL:");
    ThemeUI::tr("Tables:");
    ThemeUI::tr("Store");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded...");
    ThemeUI::tr("System Status");
    ThemeUI::tr("Learn what your system is up to.");
    ThemeUI::tr("Arclight is a sleek theme meant for widescreen HD screens.  It is high contrast and uses shapes and attractive layout to convey information simply, consistently, and attractively.");
    ThemeUI::tr("Type your tweet below.  Select \"Send\" to submit it.");
    ThemeUI::tr("Send");
    ThemeUI::tr("Enter Your Twitter Login Details");
    ThemeUI::tr("Login:");
    ThemeUI::tr("Password:");
    ThemeUI::tr("Send a Tweet");
    ThemeUI::tr("Welcome to MythTV");
    ThemeUI::tr("MythTV is idle and will shut down shortly.");
    ThemeUI::tr("Current Recording(s):");
    ThemeUI::tr("Retrieving Recording Status ...");
    ThemeUI::tr("Next Scheduled Recording(s):");
    ThemeUI::tr("Retrieving Scheduled Recordings ...");
    ThemeUI::tr("WARNING: There are conflicting scheduled recordings!");
    ThemeUI::tr("Move the selected arrow to the corner of the TV screen.  Press SELECT to edit the other arrow.  Press MENU for options and ESC to quit.");
    ThemeUI::tr("1280 x 720");
    ThemeUI::tr("0 x 0");
    ThemeUI::tr("Filename");
    ThemeUI::tr("Please Wait....");
    ThemeUI::tr("Select an Icon");
    ThemeUI::tr("Icon Download Status...");
    ThemeUI::tr("Search terms:");
    ThemeUI::tr("Sort Mode:");
    ThemeUI::tr("Icon Download");
    ThemeUI::tr("OSD Menu Editor");
    ThemeUI::tr("Contexts");
    ThemeUI::tr("Actions");
    ThemeUI::tr("This screen displays the status of various system components");
    ThemeUI::tr("%|\"SUBTITLE|\"%");
    ThemeUI::tr("No Recordings Present...");
    ThemeUI::tr("Change View");
    ThemeUI::tr("Show Titles");
    ThemeUI::tr("Show Categories");
    ThemeUI::tr("Show LiveTV");
    ThemeUI::tr("Old Password:");
    ThemeUI::tr("New Password:");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%) %LONGREPEAT%%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("Title (Optional):");
    ThemeUI::tr("Date, or day of week:");
    ThemeUI::tr("Start Time:");
    ThemeUI::tr("Hour");
    ThemeUI::tr("Minute");
    ThemeUI::tr("%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and Select 'Program Guide' or 'Program Finder' ");
    ThemeUI::tr("Channel Recording Priorities");
    ThemeUI::tr("(1) Channel (2) Priority");
    ThemeUI::tr("Priority");
    ThemeUI::tr("Source:");
    ThemeUI::tr("Final");
    ThemeUI::tr("(1) Title (2) Priority (4) Type");
    ThemeUI::tr("Existing Rules:");
    ThemeUI::tr("Priority Change:");
    ThemeUI::tr("Select a clause from the list.");
    ThemeUI::tr("Add Clause");
    ThemeUI::tr("Search Term");
    ThemeUI::tr("Select Search");
    ThemeUI::tr("Edit");
    ThemeUI::tr("Edit Power Search Fields");
    ThemeUI::tr("Optional title phrase:");
    ThemeUI::tr("Optional subtitle phrase:");
    ThemeUI::tr("Optional description phrase:");
    ThemeUI::tr("Program Details:");
    ThemeUI::tr("Show Name:");
    ThemeUI::tr("Air Date:");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("%|\"SUBTITLE|\"% %LONGREPEAT%%STARS| %%DESCRIPTION%");
    ThemeUI::tr("Select the recording rule");
    ThemeUI::tr("Preview");
    ThemeUI::tr("Reduce priority by %n", 0, 1);
    ThemeUI::tr("Normal recording priority");
    ThemeUI::tr("Raise priority by %n", 0, 1);
    ThemeUI::tr("Start recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Start recording on time");
    ThemeUI::tr("Start recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording %n minute(s) early", 0, 1);
    ThemeUI::tr("End recording on time");
    ThemeUI::tr("End recording %n minute(s) late", 0, 1);
    ThemeUI::tr("Dupe Method:");
    ThemeUI::tr("Dupe Scope:");
    ThemeUI::tr("Recording Rule Active");
    ThemeUI::tr("Back");
    ThemeUI::tr("Rec Profile:");
    ThemeUI::tr("Rec Group:");
    ThemeUI::tr("# to Keep:");
    ThemeUI::tr("No episode limit");
    ThemeUI::tr("Keep at most %n episode(s)", 0, 1);
    ThemeUI::tr("Limit Handling:");
    ThemeUI::tr("Commercial Flag new recordings");
    ThemeUI::tr("Transcode new recordings");
    ThemeUI::tr("Graphite is a theme emphasizing MythUI interface improvements such as alpha, animation, unique layouts, and user-supplied backdrop content.  It is extremely memory-hungry.");
    ThemeUI::tr("Channel Editor");
    ThemeUI::tr("Callsign");
    ThemeUI::tr("Channel #");
    ThemeUI::tr("Channel Name");
    ThemeUI::tr("XMLTV ID");
    ThemeUI::tr("[P]robe");
    ThemeUI::tr("[O]k");
    ThemeUI::tr("%DESCRIPTION%%BR%(%STARTTIME% - %LENMINS%)");
    ThemeUI::tr("A basic blue theme.");
    ThemeUI::tr("%SUBTITLE%%BR%%DESCRIPTION%");
    ThemeUI::tr("%STARTDATE%");
    ThemeUI::tr("%CALLSIGN% - %CHANNUM%");
    ThemeUI::tr("A simple transparent black and white theme.");
    ThemeUI::tr("title goes here");
    ThemeUI::tr("sep 13, 2004 11:00 pm (1h 15m)");
    ThemeUI::tr("description goes here.");
    ThemeUI::tr("x.xx GB");
    ThemeUI::tr("xxxxx MB");
    ThemeUI::tr("0 MB");
    ThemeUI::tr("File Finder To Import");
    ThemeUI::tr("Watch Recordings");
    ThemeUI::tr("%|\"SUBTITLE|\"% %STARS% %DESCRIPTION%");
    ThemeUI::tr("No Recordings available, or screen loading...");
    ThemeUI::tr("Change Recording Group Password");
    ThemeUI::tr("Status Icons");
    ThemeUI::tr("%LONGREPEAT%%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("Manual Recording Schedule");
    ThemeUI::tr("Scheduled Recordings");
    ThemeUI::tr("Showing:");
    ThemeUI::tr("%|\"SUBTITLE|\"%\n%YEARSTARS%%DESCRIPTION%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and Select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("(1) All  (2) Important");
    ThemeUI::tr("Schedule Priorities");
    ThemeUI::tr("Phrase");
    ThemeUI::tr("Program Listings");
    ThemeUI::tr("No listings found for this program.");
    ThemeUI::tr("Enter Search Text");
    ThemeUI::tr("Close");
    ThemeUI::tr("Search For:");
    ThemeUI::tr("Manage Recording Rules");
    ThemeUI::tr("Channel");
    ThemeUI::tr("Last Recorded");
    ThemeUI::tr("Custom Record Rules");
    ThemeUI::tr("Additional Tables:");
    ThemeUI::tr("Schedule Editor");
    ThemeUI::tr("Schedule Options Editor");
    ThemeUI::tr("Storage Options Editor");
    ThemeUI::tr("Allow recordings to expire?");
    ThemeUI::tr("Post Processing Editor");
    ThemeUI::tr("Run User job #2");
    ThemeUI::tr("Details");
    ThemeUI::tr("Mythbuntu is based on ProjectGrayhem - a dark, shiny theme originally inspired by XBMC's ProjectMayhem skin");
    ThemeUI::tr("MythTV is idle and will shutdown shortly.");
    ThemeUI::tr("Current Recording(s)");
    ThemeUI::tr("Next Scheduled Recording(s)");
    ThemeUI::tr("%SUBTITLE|\"|\" %%DESCRIPTION%");
    ThemeUI::tr("(%STARTTIME% - %ENDTIME%)  %LENMINS%");
    ThemeUI::tr("%CHANNUM%");
    ThemeUI::tr("%CALLSIGN%");
    ThemeUI::tr("A glossy black look to go with the ProjectGrayhem UI theme.");
    ThemeUI::tr("(%STARTDATE%)  %LENMINS%");
    ThemeUI::tr("A graded blue theme with orange text.");
    ThemeUI::tr("%LONGREPEAT%%STARS%%DESCRIPTION%");
    ThemeUI::tr("%STARTTIME%-%ENDTIME% (%LENMINS%)");
    ThemeUI::tr("Browsing");
    ThemeUI::tr("Transparent blue.");
    ThemeUI::tr("A two tone blue theme matching the blootube family of UI themes.");
    ThemeUI::tr("%TITLE% (%STARTTIME% %LENMINS%)");
    ThemeUI::tr("Red and blue.");
    ThemeUI::tr("Key Configuration");
    ThemeUI::tr("Main Menu");
    ThemeUI::tr("Utilities");
    ThemeUI::tr("Manage Recordings");
    ThemeUI::tr("Information");
    ThemeUI::tr("Optical Media");
    ThemeUI::tr("Schedule Recordings");
    ThemeUI::tr("Media Library");
    ThemeUI::tr("Music");
    ThemeUI::tr("Photographs");
    ThemeUI::tr("Setup");
    ThemeUI::tr("Media Setup");
    ThemeUI::tr("Info Setup");
    ThemeUI::tr("TV Setup");
    ThemeUI::tr("DVD");
    ThemeUI::tr("Music Setup");
    ThemeUI::tr("Video Setup");
    ThemeUI::tr("Game Setup");
    ThemeUI::tr("NetFlix");
    ThemeUI::tr("Archive");
    ThemeUI::tr("Search Words");
    ThemeUI::tr("Search Lists");
    ThemeUI::tr("NetFlix Browser");
    ThemeUI::tr("NetFlix Queue");
    ThemeUI::tr("MythFlix Configuration");
    ThemeUI::tr("Probe");
    ThemeUI::tr("%YEARSTARS% %DESCRIPTION% %LONGREPEAT%");
    ThemeUI::tr("No recordings exist");
    ThemeUI::tr("Old Password");
    ThemeUI::tr("New Password");
    ThemeUI::tr("Title");
    ThemeUI::tr("Subtitle");
    ThemeUI::tr("Manual Recording");
    ThemeUI::tr("Upcoming Recordings");
    ThemeUI::tr("%YEARSTARS| %%DESCRIPTION%%| LONGREPEAT%");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded\n To schedule a recording, exit this screen and select 'Program Guide' or 'Program Finder'");
    ThemeUI::tr("Programme Finder");
    ThemeUI::tr("Programme Guide");
    ThemeUI::tr("Previously Recorded");
    ThemeUI::tr("(1) Time (2) Title");
    ThemeUI::tr("No programs matched this search.");
    ThemeUI::tr("A brushed metal and glass effect theme with a choice of colour schemes.");
    ThemeUI::tr("Start Frontend");
    ThemeUI::tr("1. General");
    ThemeUI::tr("2. Capture cards");
    ThemeUI::tr("3. Video sources");
    ThemeUI::tr("4. Input connections");
    ThemeUI::tr("5. Channel Editor");
    ThemeUI::tr("6. Storage Directories");
    ThemeUI::tr("7. System Events");
    ThemeUI::tr("%alert_text%");
    ThemeUI::tr("LINE #%caller_line%");
    ThemeUI::tr("NAME: %caller_name%");
    ThemeUI::tr("NUM : %caller_number%");
    ThemeUI::tr("DATE: %caller_date% TIME : %caller_time%");
    ThemeUI::tr("%SUBTITLE|\"|\" %%ORIGINALAIRDATE|(|) %%YEARSTARS|| %%DESCRIPTION%");
    ThemeUI::tr("%STARTDATE%  (%STARTTIME% - %ENDTIME%)  %LENMINS%");
    ThemeUI::tr("The BlackCurves theme was influenced by both the blootube and gray osd themes.");
    ThemeUI::tr("General");
    ThemeUI::tr("Core MythTV behavior and system settings");
    ThemeUI::tr("Appearance");
    ThemeUI::tr("pick the theme, font, size, and locale");
    ThemeUI::tr("Screen Setup Wizards");
    ThemeUI::tr("Compensate for TVs with overscan");
    ThemeUI::tr("TV Settings");
    ThemeUI::tr("Settings for TV recording and playback");
    ThemeUI::tr("Music Settings");
    ThemeUI::tr("Configure playback and CD ripping");
    ThemeUI::tr("Videos Settings");
    ThemeUI::tr("Configure playback and DVD ripping");
    ThemeUI::tr("Radio Settings");
    ThemeUI::tr("Images Settings");
    ThemeUI::tr("Configure display of image gallery");
    ThemeUI::tr("Game Settings");
    ThemeUI::tr("Configure playback of games");
    ThemeUI::tr("Weather Settings");
    ThemeUI::tr("Weather locale and sources");
    ThemeUI::tr("News Settings");
    ThemeUI::tr("Choose which news sources interest you");
    ThemeUI::tr("Web Settings");
    ThemeUI::tr("Manage web bookmarks");
    ThemeUI::tr("Recipe Settings");
    ThemeUI::tr("Phone Settings");
    ThemeUI::tr("Configure SIP-based VoIP phone");
    ThemeUI::tr("Movie Time Settings");
    ThemeUI::tr("Select local movie theaters");
    ThemeUI::tr("Xbox Settings");
    ThemeUI::tr("NetFlix Settings");
    ThemeUI::tr("Choose the genres that interest you");
    ThemeUI::tr("Archive Files Settings");
    ThemeUI::tr("Configure how to archive video to DVD");
    ThemeUI::tr("ZoneMinder Settings");
    ThemeUI::tr("Set up surveillance software");
    ThemeUI::tr("Play Recordings");
    ThemeUI::tr("See what will be recorded next");
    ThemeUI::tr("Pick shows to record");
    ThemeUI::tr("Recording Priorities");
    ThemeUI::tr("Prioritize some shows over others");
    ThemeUI::tr("What your system is doing right now");
    ThemeUI::tr("Utilities / Setup");
    ThemeUI::tr("Settings for TV, Images, Music, Video, Weather, etc.");
    ThemeUI::tr("Set Recording Priorities");
    ThemeUI::tr("Settings to prioritize some shows over others");
    ThemeUI::tr("Set Channel Recording Priorities");
    ThemeUI::tr("Settings to prioritize some channels over others");
    ThemeUI::tr("Custom Priority");
    ThemeUI::tr("Most used DVR options are found on the main menu. Plugin options are in the utilities menu.");
    ThemeUI::tr("New Titles");
    ThemeUI::tr("Pick a program to record for a list of new titles");
    ThemeUI::tr("Movies");
    ThemeUI::tr("Pick a movie to record");
    ThemeUI::tr("Categories");
    ThemeUI::tr("Pick a program based on category");
    ThemeUI::tr("Channels");
    ThemeUI::tr("Pick a program on a given channel");
    ThemeUI::tr("Time");
    ThemeUI::tr("Pick a program based on time");
    ThemeUI::tr("Program Guide");
    ThemeUI::tr("Choose programs from a grid-style list");
    ThemeUI::tr("Program Finder");
    ThemeUI::tr("Choose programs from an alphabetical index");
    ThemeUI::tr("Find programs matching search words");
    ThemeUI::tr("Pick a program to record from a set of lists");
    ThemeUI::tr("Custom Record");
    ThemeUI::tr("Advanced program finder");
    ThemeUI::tr("Manual Schedule");
    ThemeUI::tr("VCR-like recording scheduler");
    ThemeUI::tr("Titles");
    ThemeUI::tr("Find a program based on title");
    ThemeUI::tr("Keywords");
    ThemeUI::tr("Find a program matching a keyword");
    ThemeUI::tr("People");
    ThemeUI::tr("Find a program including a given person");
    ThemeUI::tr("Advanced");
    ThemeUI::tr("Combine more than one word search");
    ThemeUI::tr("Stored Searches");
    ThemeUI::tr("Results of searches you have saved");
    ThemeUI::tr("TV navigation and recording preferences");
    ThemeUI::tr("Guide appearance and behavior");
    ThemeUI::tr("Playback");
    ThemeUI::tr("Settings for viewing and playing TV");
    ThemeUI::tr("Playback OSD");
    ThemeUI::tr("Theme and settings for OSD");
    ThemeUI::tr("Playback Groups");
    ThemeUI::tr("Adjust settings for different playback styles");
    ThemeUI::tr("Channel Groups");
    ThemeUI::tr("Recording Profiles");
    ThemeUI::tr("Global recording priority and scheduling");
    ThemeUI::tr("Watch TV");
    ThemeUI::tr("Watch live television");
    ThemeUI::tr("Delete Recordings");
    ThemeUI::tr("Remove television recordings");
    ThemeUI::tr("See what you have recorded before");
    ThemeUI::tr("TV Utilities");
    ThemeUI::tr("Videos");
    ThemeUI::tr("Radio");
    ThemeUI::tr("Images");
    ThemeUI::tr("Games");
    ThemeUI::tr("Weather");
    ThemeUI::tr("News Feeds");
    ThemeUI::tr("Web");
    ThemeUI::tr("Phone");
    ThemeUI::tr("Burn DVD");
    ThemeUI::tr("Recipes");
    ThemeUI::tr("Archive Files");
    ThemeUI::tr("Zone Minder");
    ThemeUI::tr("Movie Times");
    ThemeUI::tr("Edit Keys");
    ThemeUI::tr("(%TIMEDATE%)  %LENMINS%");
    ThemeUI::tr("%SUBTITLE|\"|\" %");
    ThemeUI::tr("%TITLE%");
    ThemeUI::tr("A transparent dark grey theme.");
    ThemeUI::tr("Search For");
    ThemeUI::tr("A blue theme.");
    ThemeUI::tr("Directed by:");
    ThemeUI::tr("Year:");
    ThemeUI::tr("User Rating:");
    ThemeUI::tr("Runtime:");
    ThemeUI::tr("Play");
    ThemeUI::tr("No videos in library, or no files found.  If you have configured a video directory, press \"M\" (or the MENU key) and select \"Scan for Changes.\"");
    ThemeUI::tr("Director:");
    ThemeUI::tr("Rated:");
    ThemeUI::tr("Parental Level:");
    ThemeUI::tr("Lowest");
    ThemeUI::tr("Low");
    ThemeUI::tr("Medium");
    ThemeUI::tr("High");
    ThemeUI::tr("Browsable:");
    ThemeUI::tr("Plot:");
    ThemeUI::tr("Filename:");
    ThemeUI::tr("Cover File:");
    ThemeUI::tr("Video Num.:");
    ThemeUI::tr("Directed by");
    ThemeUI::tr("Runtime");
    ThemeUI::tr("Year");
    ThemeUI::tr("User Rating");
    ThemeUI::tr("Parental Level");
    ThemeUI::tr("MythVideo File Associations");
    ThemeUI::tr("Extension:");
    ThemeUI::tr("Command:");
    ThemeUI::tr("Use default player:");
    ThemeUI::tr("Ignore:");
    ThemeUI::tr("Edit Video Information");
    ThemeUI::tr("Parental Control:");
    ThemeUI::tr("File to Always Play Next:");
    ThemeUI::tr("Include while Browsing:");
    ThemeUI::tr("Item has been watched:");
    ThemeUI::tr("Cover Art:");
    ThemeUI::tr("Screenshot:");
    ThemeUI::tr("Banner:");
    ThemeUI::tr("Fanart:");
    ThemeUI::tr("Trailer:");
    ThemeUI::tr("Unique Player Command:");
    ThemeUI::tr("/path/to/the/thing.jpg");
    ThemeUI::tr("Filters video list");
    ThemeUI::tr("Text Filter:");
    ThemeUI::tr("Category :");
    ThemeUI::tr("Genre :");
    ThemeUI::tr("Country :");
    ThemeUI::tr("Actor/Actress :");
    ThemeUI::tr("Year :");
    ThemeUI::tr("Runtime :");
    ThemeUI::tr("User Rating :");
    ThemeUI::tr("Browse :");
    ThemeUI::tr("InetRef :");
    ThemeUI::tr("Cover File :");
    ThemeUI::tr("Sort by :");
    ThemeUI::tr("Watched :");
    ThemeUI::tr("Result");
    ThemeUI::tr("Save as default");
    ThemeUI::tr("Sample Clauses:");
    ThemeUI::tr(" This was adapted from the Jeroen Brosens' MythCenter theme. The fonts have been changed to freely redistributable ones and layout changes have been made to make this theme look good on 1280x720 and 1920x1080 screens with a 1:1 pixel aspect ratio. ");
    ThemeUI::tr("Heading");
    ThemeUI::tr("Playback starting...");
    ThemeUI::tr("Bookmark Manager");
    ThemeUI::tr("Web Page");
    ThemeUI::tr("Icon Importer");
    ThemeUI::tr("List Options");
    ThemeUI::tr("Delete All");
    ThemeUI::tr("Global Options");
    ThemeUI::tr("Image Gallery");
    ThemeUI::tr("No images found in configured directory.  Are you sure you have set up the plugin properly?");
    ThemeUI::tr("Play Games");
    ThemeUI::tr("System:");
    ThemeUI::tr("Favorite:");
    ThemeUI::tr("Yes");
    ThemeUI::tr("No");
    ThemeUI::tr("Emulator:");
    ThemeUI::tr("Television");
    ThemeUI::tr("Gallery");
    ThemeUI::tr("Schedule");
    ThemeUI::tr("Programme Searches");
    ThemeUI::tr("CD/DVD Options");
    ThemeUI::tr("Info Centre");
    ThemeUI::tr("P");
    ThemeUI::tr("S");
    ThemeUI::tr("Playing:");
    ThemeUI::tr("None");
    ThemeUI::tr("Internet Video Browser");
    ThemeUI::tr("No sites configured!");
    ThemeUI::tr("Videos - Gallery");
    ThemeUI::tr("Videos - Tree");
    ThemeUI::tr("%|\"SUBTITLE|\"% %DESCRIPTION%");
    ThemeUI::tr("Change Displayed Groups");
    ThemeUI::tr("Show Watched Recordings");
    ThemeUI::tr("Schedules Overview");
    ThemeUI::tr("First Conflict:");
    ThemeUI::tr("Recording Rule Priorities");
    ThemeUI::tr("Type");
    ThemeUI::tr("List Overview");
    ThemeUI::tr("Current View:");
    ThemeUI::tr("Position:");
    ThemeUI::tr("Rule Overview");
    ThemeUI::tr("Post-Processing Options");
    ThemeUI::tr("Search Results");
    ThemeUI::tr("Cast Members");
    ThemeUI::tr("Full Plot");
    ThemeUI::tr("Video List Filters");
    ThemeUI::tr("Category");
    ThemeUI::tr("Genre");
    ThemeUI::tr("Country");
    ThemeUI::tr("Actor/Actress");
    ThemeUI::tr("Browse");
    ThemeUI::tr("InetRef");
    ThemeUI::tr("Cover File");
    ThemeUI::tr("Sort by");
    ThemeUI::tr("Watched");
    ThemeUI::tr("Make default");
    ThemeUI::tr("Video Manager");
    ThemeUI::tr("Parental:");
    ThemeUI::tr("IMDB ID:");
    ThemeUI::tr("Video Browser");
    ThemeUI::tr("Video File Associations");
    ThemeUI::tr("Edit Video Metadata");
    ThemeUI::tr("Item has been Watched:");
    ThemeUI::tr("Change mythtv key bindings.");
    ThemeUI::tr("MythStream Settings");
    ThemeUI::tr("Weather Station Settings");
    ThemeUI::tr("TV");
    ThemeUI::tr("Internet Video");
    ThemeUI::tr("Play Online Streams");
    ThemeUI::tr("Weather Station");
    ThemeUI::tr("A long menu which breaks down the options by their category. TV, Music, Video etc");
    ThemeUI::tr("Search Listings");
    ThemeUI::tr("Recording Rules");
    ThemeUI::tr("Edit or delete any recording rule");
    ThemeUI::tr("Play TV Recordings");
    ThemeUI::tr("Preview Schedule Changes");
    ThemeUI::tr("You Haven't Scheduled Any Programs To Be Recorded");
    ThemeUI::tr("(1)Time (2)Title");
    ThemeUI::tr("Keep up with the news");
    ThemeUI::tr("Twitter");
    ThemeUI::tr("Send and receive tweets");
    ThemeUI::tr("See when local movies are playing");
    ThemeUI::tr("Local weather forecast");
    ThemeUI::tr("Manage your NetFlix queue");
    ThemeUI::tr("Browse the web");
    ThemeUI::tr("Start cooking!");
    ThemeUI::tr("See what your system is doing");
    ThemeUI::tr("Home surveillance");
    ThemeUI::tr("Hardware profile");
    ThemeUI::tr("Tell us what hardware you have so we can support it");
    ThemeUI::tr("Browse your recordings");
    ThemeUI::tr("Watch Videos");
    ThemeUI::tr("Browse your video library");
    ThemeUI::tr("Listen to Music");
    ThemeUI::tr("Browse your music library");
    ThemeUI::tr("Listen to the radio");
    ThemeUI::tr("Search Internet Video");
    ThemeUI::tr("Search popular video sites");
    ThemeUI::tr("Browse Internet Video");
    ThemeUI::tr("Browse highlights and entire sites");
    ThemeUI::tr("Look at Pictures");
    ThemeUI::tr("Play video games");
    ThemeUI::tr("Pick the theme, font, size, and locale");
    ThemeUI::tr("Media Settings");
    ThemeUI::tr("Settings for all non-TV media");
    ThemeUI::tr("Info Center Settings");
    ThemeUI::tr("Configure weather, news, movie info, web, and recipes");
    ThemeUI::tr("System Event Handlers");
    ThemeUI::tr("Configure System Event handler commands");
    ThemeUI::tr("Play any of your media");
    ThemeUI::tr("Pick and prioritize recordings");
    ThemeUI::tr("Information Center");
    ThemeUI::tr("Information and Communications");
    ThemeUI::tr("Optical Disks");
    ThemeUI::tr("Play or import CDs and DVDs");
    ThemeUI::tr("Configure MythTV and plugins");
    ThemeUI::tr("See what you have recorded");
    ThemeUI::tr("Set Priorities");
    ThemeUI::tr("Play DVD");
    ThemeUI::tr("Play a film on DVD");
    ThemeUI::tr("Play VCD");
    ThemeUI::tr("Play the video on a VCD");
    ThemeUI::tr("Import DVD");
    ThemeUI::tr("Import video from a movie DVD");
    ThemeUI::tr("Write video to a data DVD");
    ThemeUI::tr("Import CD");
    ThemeUI::tr("Import music from an audio CD");
    ThemeUI::tr("Eject media");
    ThemeUI::tr("Eject CD or DVD from drive");
    ThemeUI::tr("Prioritize some channels over others");
    ThemeUI::tr("Prioritize some recordings over others");
    ThemeUI::tr("Choose which menu options appear during playback");
    ThemeUI::tr("Group your favorite channels together");
    ThemeUI::tr("Change the quality of your recordings");
    ThemeUI::tr("Music Tools");
    ThemeUI::tr("Select, import, or play music");
    ThemeUI::tr("Change MythTV key bindings.");
    ThemeUI::tr("(%STARTDATE% %STARTTIME% - %ENDTIME%)  %LENMINS%");
    ThemeUI::tr("A very simple blue and black theme.");
    ThemeUI::tr("Pick and prioritize shows to record");
    ThemeUI::tr("Play or import audio or video CDs or DVDs");
    ThemeUI::tr("Play recordings");
    ThemeUI::tr("Play videos");
    ThemeUI::tr("Watch A DVD");
    ThemeUI::tr("Play the video on a movie DVD");
    ThemeUI::tr("Watch Live TV");
    ThemeUI::tr("Watch Online Streams");
    ThemeUI::tr("Plugins");
    ThemeUI::tr("Other Plugins");
    ThemeUI::tr("Advanced Options");
    ThemeUI::tr("A \"Media Center\" menu theme. This menu theme is basically meant to bring the common \"media player/DVR\" functionality to the forefront, organize the plugins, and to make some of myth's more daunting options a little more subtle. Places the common media items on the top level (Recordings, Videos, TV, DVD, Music), places all informational plugins in \"Plugins.\" Puts all setup and scheduling in \"Advanced.\" The top two menu levels will seem new, the ones beneath Advanced->Setup are as in the default menu.");
}
