######################################################################
# Automatically generated by qmake (1.03a) Sat Aug 31 10:10:35 2002
######################################################################

TEMPLATE = app
CONFIG += thread
CONFIG -= moc
TARGET = mythfilldatabase
target.path = /usr/local/bin
INSTALLS = target

include ( ../settings.pro )

INCLUDEPATH += ../libNuppelVideo

# Input
HEADERS += ../libNuppelVideo/settings.h
SOURCES += filldata.cpp ../libNuppelVideo/settings.cpp
