name: fixes/31

on:
  push:
    branches: [ fixes/31 ]
  pull_request:
    branches: [ fixes/31 ]

jobs:
  build:
    name: build
    strategy:
      matrix:
        os: ['ubuntu-18.04']
        cc: ['gcc', 'clang']
        include:
          - cc: 'gcc'
            cxx: 'g++'
          - cc: 'clang'
            cxx: 'clang++'  
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout fixes/31
      uses: actions/checkout@v2
      
    - name: Setup build environment
      run: echo "MYTHTV_CONFIG=--prefix=${{ github.workspace }}/build/install --cc=${{ matrix.cc }} --cxx=${{ matrix.cxx }}" >> $GITHUB_ENV
      
    - name: Check ccache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ matrix.os }}-${{ matrix.cc }}-ccache-${{ github.sha }}
        restore-keys: ${{ matrix.os }}-${{ matrix.cc }}-ccache
  
    # N.B. These dependencies are for the fixes/31 branch. The list is intended to provide as much code coverage as possible (i.e. enable as many options as possible)
    - name: Install core dependencies (linux)
      run: |
        sudo apt update
        sudo apt install ccache qt5-qmake qtscript5-dev nasm libsystemd-dev libfreetype6-dev libmp3lame-dev libx264-dev libx265-dev libxrandr-dev libxml2-dev libavahi-compat-libdnssd-dev libasound2-dev liblzo2-dev libhdhomerun-dev libsamplerate0-dev libva-dev libdrm-dev libvdpau-dev libass-dev libpulse-dev libcec-dev libfftw3-dev libssl-dev libtag1-dev libbluray-dev libbluray-bdj libgnutls28-dev libqt5webkit5-dev libvpx-dev python3-mysqldb python3-lxml python3-simplejson python3-future libdbi-perl libdbd-mysql-perl libnet-upnp-perl libio-socket-inet6-perl libxml-simple-perl libqt5sql5-mysql libxxf86vm-dev libxinerama-dev libexiv2-dev
      if: runner.os == 'Linux'
      
    - name: Install core dependencies (macOS)
      run: |
        brew install pkg-config ccache qt5 nasm libsamplerate taglib lzo libcec libbluray fftw libass libhdhomerun dav1d x264 x265 libvpx openssl exiv2
        brew link qt5 --force
        echo "MYTHTV_CONFIG=$MYTHTV_CONFIG --extra-cxxflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib" >> $GITHUB_ENV
      if: runner.os == 'macOS'
      
    - name: Configure core
      working-directory: ./mythtv
      run: ./configure $MYTHTV_CONFIG --enable-libmp3lame --enable-libvpx --enable-libx264 --enable-libx265 --enable-bdjava
      
    - name: Make core
      working-directory: ./mythtv
      run: make all_no_test -j4
    
    - name: Install core
      working-directory: ./mythtv
      run: make install
      
    # QTest requires a QT SQL plugin - but there are currently none available via brew on macOS
    - name: Unit test core
      working-directory: ./mythtv
      run: make test
      if: runner.os == 'Linux'
    
    - name: Install plugin dependencies (linux)
      run: sudo apt install libvorbis-dev libflac++-dev libminizip-dev libcdio-dev libcdio-paranoia-dev python3-oauth python3-pycurl
           libxml-xpath-perl libdate-manip-perl libdatetime-format-iso8601-perl libsoap-lite-perl libjson-perl libimage-size-perl
      if: runner.os == 'Linux'
      
    - name: Install plugin dependencies (macOS)
      run: brew install minizip flac libvorbis libcdio
      if: runner.os == 'macOS'
      
    - name: Configure plugins
      working-directory: ./mythplugins
      run: ./configure $MYTHTV_CONFIG
    
    - name: Make plugins
      working-directory: ./mythplugins
      run: make -j4
