
all: 6200ch_all dct-channel_all red_eye_all sa3250ch_all
clean: 6200ch_clean dct-channel_clean red_eye_clean sa3250ch_clean
install: 6200ch_install change-channel-lirc_install d10control_install dct-channel_install dct2000serial_install red_eye_install sa3250ch_install
uninstall: 6200ch_uninstall change-channel-lirc_uninstall d10control_uninstall dct-channel_uninstall dct2000serial_uninstall red_eye_uninstall sa3250ch_uninstall

6200ch_all:
	cd 6200ch && $(MAKE) all

dct-channel_all:
	cd dct-channel && $(MAKE) all

red_eye_all:
	cd red_eye && $(MAKE) all

sa3250ch_all:
	cd sa3250ch && $(MAKE) all


6200ch_clean:
	cd 6200ch && $(MAKE) clean

dct-channel_clean:
	cd dct-channel && $(MAKE) clean

red_eye_clean:
	cd red_eye && $(MAKE) clean

sa3250ch_clean:
	cd sa3250ch && $(MAKE) clean


6200ch_install:
	cd 6200ch && $(MAKE) install

change-channel-lirc_install:
	cd change-channel-lirc && $(MAKE) install

d10control_install:
	cd d10control && $(MAKE) install

dct-channel_install:
	cd dct-channel && $(MAKE) install

dct2000serial_install:
	cd dct2000serial && $(MAKE) install

red_eye_install:
	cd red_eye && $(MAKE) install

sa3250ch_install:
	cd sa3250ch && $(MAKE) install


6200ch_uninstall:
	cd 6200ch && $(MAKE) uninstall

change-channel-lirc_uninstall:
	cd change-channel-lirc && $(MAKE) uninstall

d10control_uninstall:
	cd d10control && $(MAKE) uninstall

dct-channel_uninstall:
	cd dct-channel && $(MAKE) uninstall

dct2000serial_uninstall:
	cd dct2000serial && $(MAKE) uninstall

red_eye_uninstall:
	cd red_eye && $(MAKE) uninstall

sa3250ch_uninstall:
	cd sa3250ch && $(MAKE) uninstall
